// angular/src/app/components/app-header/app-header.component.ts
import { Component, Input, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, NavigationEnd } from '@angular/router';
import { filter, map } from 'rxjs/operators';
import { BrandLogoComponent } from '../brand-logo/brand-logo.component';
import { APP_VERSION } from '../../version';
import { DebugPanelService } from '../debug-panel/debug-panel.service';
import { WizardStateService } from '../../core/services/wizard-state.service';

export interface HeaderAction {
  label: string;
  onClick: () => void;
  variant?: 'primary' | 'secondary' | 'danger';
  icon?: string;
}

export interface StoreInfo {
  name?: string;
  type: 'single' | 'multi';
  count?: number;
}

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, BrandLogoComponent],
  templateUrl: './app-header.component.html',
  styleUrls: ['./app-header.component.scss'],
})
export class AppHeaderComponent implements OnInit, OnDestroy {
  @Input() wizardCompleted = false;
  @Input() set currentPage(value: 'income' | 'expenses' | 'reports' | 'dashboard') {
    console.log('📊 Header received currentPage:', value);
    this._currentPage = value;
  }
  get currentPage(): 'income' | 'expenses' | 'reports' | 'dashboard' {
    return this._currentPage;
  }
  private _currentPage: 'income' | 'expenses' | 'reports' | 'dashboard' = 'dashboard';
  // Optional presentational inputs to mirror React AppHeader features (no business logic here)
  @Input() breadcrumb?: Array<{ label: string; onClick?: () => void }>;
  @Input() actions?: HeaderAction[];
  @Input() storeInfo?: StoreInfo;

  private navSub?: any;
  readonly appVersion = APP_VERSION;
  readonly debugOpen$ = this.debugSvc.open$;

  // Get region from WizardStateService for reactive updates
  readonly region$ = this.wizardState.answers$.pipe(map((answers) => answers.region || 'US'));

  constructor(
    private router: Router,
    private debugSvc: DebugPanelService,
    private wizardState: WizardStateService
  ) {}

  ngOnInit(): void {
    const derive = (url: string): 'income' | 'expenses' | 'reports' | 'dashboard' => {
      if (url.includes('/wizard/income-drivers')) return 'income';
      if (url.includes('/wizard/expenses')) return 'expenses';
      if (url.includes('/wizard/pnl')) return 'reports';
      return 'dashboard';
    };

    this.currentPage = derive(this.router.url);
    this.navSub = this.router.events
      .pipe(filter((e): e is NavigationEnd => e instanceof NavigationEnd))
      .subscribe((e) => {
        this.currentPage = derive(e.urlAfterRedirects || e.url);
      });
  }

  ngOnDestroy(): void {
    if (this.navSub && typeof this.navSub.unsubscribe === 'function') {
      this.navSub.unsubscribe();
    }
  }

  goIncome(): void {
    console.log('🎯 [HEADER] Navigating to income drivers...');
    this.router.navigateByUrl('/wizard/income-drivers');
  }

  goDashboard(): void {
    console.log('🎯 [HEADER] Navigating to dashboard...');
    this.router.navigateByUrl('/dashboard');
  }

  goReports(): void {
    console.log('🎯 [HEADER] Navigating to reports...');
    this.router.navigateByUrl('/wizard/pnl');
  }

  goExpenses(): void {
    console.log('🎯 [HEADER] Navigating to expenses...');
    this.router.navigateByUrl('/wizard/expenses');
  }

  resetWizard(): void {
    try {
      // Clear all wizard-related localStorage
      localStorage.removeItem('wizard_state_v1');
      localStorage.removeItem('pnl_settings_v1');
      localStorage.clear();
    } catch {}
    location.reload();
  }

  toggleDebug(): void {
    this.debugSvc.toggle();
  }

  actionStyle(a?: HeaderAction['variant']): Record<string, string> {
    switch (a) {
      case 'primary':
        return { backgroundColor: '#3b82f6', color: 'white', border: '1px solid #3b82f6' };
      case 'danger':
        return { backgroundColor: '#ef4444', color: 'white', border: '1px solid #ef4444' };
      default:
        return { backgroundColor: 'white', color: '#374151', border: '1px solid #d1d5db' };
    }
  }

  get hasBreadcrumb(): boolean {
    return !!this.breadcrumb && this.breadcrumb.length > 0;
  }
}

<header class="header">
  <div style="display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:2rem;width:100%">
    <div style="justify-self:start">
      <app-brand-logo [region]="(region$ | async) || 'US'" variant="wide" size="large"></app-brand-logo>
    </div>
  <div style="display:flex;flex-direction:column;align-items:center;justify-self:center">
    <!-- Breadcrumb (optional) -->
    <div *ngIf="hasBreadcrumb" style="font-size:0.875rem;color:#6b7280;margin-bottom:0.25rem;display:flex;gap:0.5rem;align-items:center;">
      <ng-container *ngFor="let item of breadcrumb!; let last = last">
        <button *ngIf="item.onClick; else crumbText" (click)="item.onClick()" style="background:none;border:none;color:#3b82f6;cursor:pointer;text-decoration:underline;padding:0;font-size:inherit">{{ item.label }}</button>
        <ng-template #crumbText><span>{{ item.label }}</span></ng-template>
        <span *ngIf="!last" style="color:#d1d5db">→</span>
      </ng-container>
    </div>

    <div class="h2 brand" style="color:#1e40af;line-height:1.2;text-align:center">Liberty Tax • P&L Budget & Forecast</div>
    <span class="small text-xs" style="background:#f3f4f6;padding:0.25rem 0.5rem;border-radius:4px;margin-top:0.25rem">v{{ appVersion }} preview</span>
  </div>
    <div style="display:flex;flex-direction:column;align-items:end;gap:0.5rem;justify-self:end;min-width:220px">
      <div style="display:flex;align-items:center;gap:0.5rem">
        <button (click)="goIncome()" class="btn {{ currentPage==='income' ? 'btn--active' : 'btn--nav' }}" title="Income Drivers">Income</button>
        <button (click)="goExpenses()" class="btn {{ currentPage==='expenses' ? 'btn--active' : 'btn--nav' }}" title="Expenses">Expenses</button>
        <button (click)="goReports()" class="btn {{ currentPage==='reports' ? 'btn--active' : 'btn--nav' }}" title="P&L Reports">Reports</button>
      </div>
      <div style="display:flex;align-items:center;gap:0.5rem;flex-wrap:wrap">
        <!-- Optional store pill -->
        <span *ngIf="storeInfo" [ngStyle]="{
            backgroundColor: storeInfo.type === 'multi' ? '#dbeafe' : '#f0fdf4',
            color: storeInfo.type === 'multi' ? '#1e40af' : '#15803d',
            padding: '0.25rem 0.5rem', borderRadius: '4px', fontSize: '0.8rem', fontWeight: 500
          }">
          {{ storeInfo.type === 'multi' ? ('🏢 ' + (storeInfo.count || 1) + ' Stores') : ('🏪 ' + (storeInfo.name || 'Single Store')) }}
        </span>
        <button (click)="goDashboard()" class="btn {{ currentPage==='dashboard' ? 'btn--active' : 'btn--nav' }}" title="Dashboard">Dashboard</button>
        <button (click)="resetWizard()" class="btn btn--reset" title="Reset Wizard will clear Income, Expenses, and P&L pages.">Reset Wizard</button>
        <button (click)="toggleDebug()" class="btn {{ (debugOpen$|async) ? 'btn--active' : 'btn--nav' }}" title="Toggle Debug Panel">Debug</button>
        <!-- Optional actions -->
        <ng-container *ngIf="actions?.length">
          <button *ngFor="let a of actions" (click)="a.onClick()" [ngStyle]="actionStyle(a.variant)" style="padding:0.5rem 1rem;border-radius:6px;font-size:0.875rem;font-weight:500;cursor:pointer;display:flex;align-items:center;gap:0.5rem;transition:all 0.2s ease">
            <span *ngIf="a.icon">{{ a.icon }}</span>
            {{ a.label }}
          </button>
        </ng-container>
      </div>
    </div>
  </div>
</header>

// src/components/Shared/AppHeader.tsx
// AppHeader.tsx - Reusable header component for consistent branding across all views
// Works for wizard, dashboard, forecasting, multi-store, etc.

import React from 'react'

export interface HeaderAction {
  label: string
  onClick: () => void
  variant?: 'primary' | 'secondary' | 'danger'
  icon?: string
}

interface AppHeaderProps {
  title: string
  subtitle?: string
  version?: string
  region?: string
  storeInfo?: {
    name?: string
    type: 'single' | 'multi'
    count?: number
  }
  actions?: HeaderAction[]
  breadcrumb?: Array<{
    label: string
    onClick?: () => void
  }>
}

export default function AppHeader({ 
  title, 
  subtitle, 
  version,
  region,
  storeInfo,
  actions = [],
  breadcrumb
}: AppHeaderProps) {
  
  const getActionStyles = (variant: HeaderAction['variant'] = 'secondary') => {
    switch (variant) {
      case 'primary':
        return {
          backgroundColor: '#3b82f6',
          color: 'white',
          border: '1px solid #3b82f6'
        }
      case 'danger':
        return {
          backgroundColor: '#ef4444',
          color: 'white', 
          border: '1px solid #ef4444'
        }
      default:
        return {
          backgroundColor: 'white',
          color: '#374151',
          border: '1px solid #d1d5db'
        }
    }
  }

  return (
    <div style={{
      borderBottom: '1px solid #e5e7eb',
      backgroundColor: 'white',
      padding: '1rem 1.5rem',
      marginBottom: '1rem'
    }}>
      {/* Breadcrumb */}
      {breadcrumb && breadcrumb.length > 0 && (
        <div style={{ 
          fontSize: '0.875rem',
          color: '#6b7280',
          marginBottom: '0.5rem',
          display: 'flex',
          alignItems: 'center',
          gap: '0.5rem'
        }}>
          {breadcrumb.map((item, index) => (
            <React.Fragment key={index}>
              {item.onClick ? (
                <button
                  onClick={item.onClick}
                  style={{
                    background: 'none',
                    border: 'none',
                    color: '#3b82f6',
                    cursor: 'pointer',
                    textDecoration: 'underline',
                    padding: 0,
                    fontSize: 'inherit'
                  }}
                >
                  {item.label}
                </button>
              ) : (
                <span>{item.label}</span>
              )}
              {index < breadcrumb.length - 1 && (
                <span style={{ color: '#d1d5db' }}>→</span>
              )}
            </React.Fragment>
          ))}
        </div>
      )}

      {/* Header Content */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start'
      }}>
        {/* Title Section */}
        <div>
          <div style={{ 
            display: 'flex', 
            alignItems: 'center',
            gap: '1rem',
            marginBottom: '0.25rem'
          }}>
            <h1 style={{
              fontSize: '1.5rem',
              fontWeight: 600,
              color: '#111827',
              margin: 0,
              fontFamily: 'var(--brand-font-stack, "Proxima Nova", "Inter", Arial, sans-serif)'
            }}>
              {title}
            </h1>
            
            {version && (
              <span style={{
                fontSize: '0.75rem',
                color: '#6b7280',
                backgroundColor: '#f3f4f6',
                padding: '0.25rem 0.5rem',
                borderRadius: '4px',
                fontWeight: 500
              }}>
                {version}
              </span>
            )}
          </div>

          {subtitle && (
            <p style={{
              color: '#6b7280',
              margin: '0 0 0.75rem 0',
              fontSize: '1rem'
            }}>
              {subtitle}
            </p>
          )}

          {/* Store & Region Info */}
          <div style={{ 
            display: 'flex',
            gap: '1rem',
            fontSize: '0.875rem',
            color: '#374151'
          }}>
            {region && (
              <div style={{ 
                display: 'flex', 
                alignItems: 'center',
                gap: '0.25rem'
              }}>
                <span style={{ fontWeight: 500 }}>Region:</span>
                <select 
                  value={region}
                  style={{
                    border: '1px solid #d1d5db',
                    borderRadius: '4px',
                    padding: '0.25rem 0.5rem',
                    fontSize: '0.875rem',
                    backgroundColor: 'white'
                  }}
                  // onChange would be handled by parent component
                >
                  <option value="US">🇺🇸 United States</option>
                  <option value="CA">🇨🇦 Canada</option>
                </select>
              </div>
            )}

            {storeInfo && (
              <div style={{ 
                display: 'flex', 
                alignItems: 'center',
                gap: '0.25rem'
              }}>
                <span style={{ fontWeight: 500 }}>Store:</span>
                <span style={{
                  backgroundColor: storeInfo.type === 'multi' ? '#dbeafe' : '#f0fdf4',
                  color: storeInfo.type === 'multi' ? '#1e40af' : '#15803d',
                  padding: '0.25rem 0.5rem',
                  borderRadius: '4px',
                  fontSize: '0.8rem',
                  fontWeight: 500
                }}>
                  {storeInfo.type === 'multi' ? 
                    `🏢 ${storeInfo.count} Stores` : 
                    `🏪 ${storeInfo.name || 'Single Store'}`
                  }
                </span>
              </div>
            )}
          </div>
        </div>

        {/* Actions */}
        {actions.length > 0 && (
          <div style={{ 
            display: 'flex',
            gap: '0.75rem',
            alignItems: 'center'
          }}>
            {actions.map((action, index) => (
              <button
                key={index}
                onClick={action.onClick}
                style={{
                  ...getActionStyles(action.variant),
                  padding: '0.5rem 1rem',
                  borderRadius: '6px',
                  fontSize: '0.875rem',
                  fontWeight: 500,
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.5rem',
                  transition: 'all 0.2s ease'
                }}
              >
                {action.icon && <span>{action.icon}</span>}
                {action.label}
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
