// angular/legacy/react-app-main-reference/src/components/DebugSystem/DebugSidebar.tsx
// DebugSidebar.tsx - Collapsible debug sidebar with multiple views
// Professional debug interface that doesn't interfere with main UI

import React, { useState } from 'react'
import type { Thresholds } from '../../lib/calcs'
import { presets } from '../../data/presets'
import type { Scenario } from '../../data/presets'
import SuggestionManager from './SuggestionManager'

interface DebugSidebarProps {
  isOpen: boolean
  onClose: () => void
  
  // Debug data
  storageKey: string
  origin: string
  appVersion: string
  isReady: boolean
  isHydrating: boolean
  savedAt: string
  
  // Actions
  onSaveNow: () => void
  onDumpStorage: () => void
  onCopyJSON: () => void
  onClearStorage: () => void
  onShowWizard: () => void
  
  // Additional debug data
  calculations?: any
  appState?: any
  
  // Thresholds data and actions
  thresholds?: Thresholds
  onUpdateThresholds?: (thresholds: Thresholds) => void
  
  // Preset controls
  onApplyPreset?: (preset: any) => void
  onResetDefaults?: () => void
}

type DebugView = 'storage' | 'calculations' | 'state' | 'performance' | 'thresholds' | 'suggestions'

export default function DebugSidebar(props: DebugSidebarProps) {
  const {
    isOpen, onClose, storageKey, origin, appVersion, isReady, isHydrating, savedAt,
    onSaveNow, onDumpStorage, onCopyJSON, onClearStorage, onShowWizard,
    calculations, appState, thresholds, onUpdateThresholds, onApplyPreset, onResetDefaults
  } = props

  const [activeView, setActiveView] = useState<DebugView>('storage')

  if (!isOpen) return null

  const sidebarStyle: React.CSSProperties = {
    position: 'fixed',
    top: 0,
    right: 0,
    width: 350,
    height: '100vh',
    background: 'linear-gradient(135deg, #1f2937 0%, #111827 100%)',
    color: '#f9fafb',
    boxShadow: '-4px 0 20px rgba(0,0,0,0.3)',
    zIndex: 9999,
    transform: isOpen ? 'translateX(0)' : 'translateX(100%)',
    transition: 'transform 0.3s ease-in-out',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: 'monospace',
    fontSize: 12,
  }

  const headerStyle: React.CSSProperties = {
    padding: '16px',
    borderBottom: '1px solid #374151',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    background: '#111827',
  }

  const tabsStyle: React.CSSProperties = {
    display: 'flex',
    borderBottom: '1px solid #374151',
    background: '#1f2937',
  }

  const tabStyle = (active: boolean): React.CSSProperties => ({
    flex: 1,
    padding: '8px 12px',
    border: 'none',
    background: active ? '#374151' : 'transparent',
    color: active ? '#f9fafb' : '#9ca3af',
    cursor: 'pointer',
    fontSize: 11,
    transition: 'all 0.2s ease',
  })

  const contentStyle: React.CSSProperties = {
    flex: 1,
    padding: '16px',
    overflow: 'auto',
  }

  const buttonStyle: React.CSSProperties = {
    padding: '6px 12px',
    margin: '4px 0',
    background: '#374151',
    color: '#f9fafb',
    border: 'none',
    borderRadius: 4,
    cursor: 'pointer',
    fontSize: 11,
    transition: 'background 0.2s ease',
  }

  const renderStorageView = () => (
    <div>
      <div style={{ marginBottom: 16, padding: 8, backgroundColor: '#0f172a', borderRadius: 4 }}>
        <div style={{ fontSize: 10, color: '#94a3b8', marginBottom: 8 }}>
          📝 <strong>What is this?</strong> Your data is automatically saved to your browser's local storage. 
          This shows the status of your saved data and lets you manage it.
        </div>
      </div>

      <div style={{ marginBottom: 16 }}>
        <div style={{ fontWeight: 'bold', marginBottom: 8, color: '#f59e0b' }}>💾 Storage Status</div>
        <div style={{ fontSize: 10, color: '#9ca3af', marginBottom: 4 }}>Storage Key:</div>
        <div style={{ marginBottom: 8, wordBreak: 'break-all' }}>{storageKey}</div>
        
        <div style={{ fontSize: 10, color: '#9ca3af', marginBottom: 4 }}>App Version:</div>
        <div style={{ marginBottom: 8 }}>{appVersion}</div>
        
        <div style={{ fontSize: 10, color: '#9ca3af', marginBottom: 4 }}>System Status:</div>
        <div style={{ marginBottom: 8 }}>
          Ready: {isReady ? '✅' : '❌'} | Loading: {isHydrating ? '🔄' : '✅'}
        </div>
        
        <div style={{ fontSize: 10, color: '#9ca3af', marginBottom: 4 }}>Last Auto-Save:</div>
        <div style={{ marginBottom: 8, color: savedAt === '(never)' ? '#ef4444' : '#10b981' }}>{savedAt}</div>
      </div>

      <div style={{ marginBottom: 16 }}>
        <div style={{ fontWeight: 'bold', marginBottom: 8, color: '#10b981' }}>🔧 Quick Actions</div>
        <div style={{ display: 'grid', gap: 4 }}>
          <button style={buttonStyle} onClick={onSaveNow} title="Force save your current data now">
            💾 Save Now
          </button>
          <button style={buttonStyle} onClick={onDumpStorage} title="Print all saved data to browser console for debugging">
            🖥️ Dump to Console
          </button>
          <button style={buttonStyle} onClick={onCopyJSON} title="Copy all your data as JSON to clipboard">
            📋 Copy JSON
          </button>
          <button style={buttonStyle} onClick={onShowWizard} title="Restart the setup wizard">
            🧙‍♂️ Reopen Wizard
          </button>
          <button 
            style={{...buttonStyle, backgroundColor: '#dc2626', marginTop: 8}} 
            onClick={onClearStorage} 
            title="⚠️ WARNING: This will delete ALL your saved data!"
          >
            🗑️ Clear All Data
          </button>
        </div>
      </div>
    </div>
  )

  const renderCalculationsView = () => {
    // KPI Strategic Analysis for debugging
    const debugKPIStrategic = () => {
      if (!calculations || !appState) return null
      
      const revenuePerReturn = calculations.totalRevenue > 0 && appState.taxPrepReturns > 0 
        ? calculations.totalRevenue / appState.taxPrepReturns 
        : 0
        
      const cprGreenMin = revenuePerReturn * 0.745  // 74.5%
      const cprGreenMax = revenuePerReturn * 0.775  // 77.5%
      const nimGreenMin = 22.5
      const nimGreenMax = 25.5
      
      return (
        <div style={{ marginBottom: 16, padding: 8, backgroundColor: '#0f172a', borderRadius: 4, fontSize: 10 }}>
          <div style={{ color: '#f59e0b', fontWeight: 'bold', marginBottom: 8 }}>🎯 KPI Strategic Analysis</div>
          <div style={{ color: '#94a3b8' }}>
            <div style={{ marginBottom: 4 }}><strong>Revenue per Return:</strong> ${revenuePerReturn.toFixed(2)}</div>
            <div style={{ marginBottom: 4 }}>
              <strong>Cost/Return Strategic Range:</strong> ${cprGreenMin.toFixed(2)} - ${cprGreenMax.toFixed(2)} (GREEN)
            </div>
            <div style={{ marginBottom: 4 }}>
              <strong>Actual Cost/Return:</strong> ${calculations.costPerReturn?.toFixed(2)} 
              <span style={{ 
                color: calculations.cprStatus === 'green' ? '#10b981' : 
                      calculations.cprStatus === 'yellow' ? '#f59e0b' : '#ef4444',
                fontWeight: 'bold',
                marginLeft: 4
              }}>
                ({calculations.cprStatus?.toUpperCase()})
              </span>
            </div>
            <div style={{ marginBottom: 4 }}>
              <strong>Net Margin Strategic Range:</strong> {nimGreenMin}% - {nimGreenMax}% (GREEN)
            </div>
            <div style={{ marginBottom: 4 }}>
              <strong>Actual Net Margin:</strong> {calculations.netMarginPct?.toFixed(1)}%
              <span style={{ 
                color: calculations.nimStatus === 'green' ? '#10b981' : 
                      calculations.nimStatus === 'yellow' ? '#f59e0b' : '#ef4444',
                fontWeight: 'bold',
                marginLeft: 4
              }}>
                ({calculations.nimStatus?.toUpperCase()})
              </span>
            </div>
            <div style={{ fontSize: 9, color: '#6b7280', marginTop: 8 }}>
              💡 <strong>Expected Result:</strong> When Page 2 shows green, Dashboard should show all green KPIs
            </div>
          </div>
        </div>
      )
    }

    return (
      <div>
        <div style={{ marginBottom: 16, padding: 8, backgroundColor: '#0f172a', borderRadius: 4 }}>
          <div style={{ fontSize: 10, color: '#94a3b8', marginBottom: 8 }}>
            🧮 <strong>What is this?</strong> Shows how your P&L numbers are calculated from your inputs. 
            Use this to verify calculations or troubleshoot unexpected results.
          </div>
        </div>

        {debugKPIStrategic()}

        <div style={{ fontWeight: 'bold', marginBottom: 8, color: '#8b5cf6' }}>📊 Current Calculations</div>
        {calculations ? (
          <div>
            <div style={{ marginBottom: 12, fontSize: 11 }}>
              <div style={{ color: '#10b981', fontWeight: 'bold' }}>Key Results:</div>
              <div>Net Income: ${calculations.netIncome?.toLocaleString() || 'N/A'}</div>
              <div>Net Margin: {calculations.netMarginPct?.toFixed(1) || 'N/A'}%</div>
              <div>Cost/Return: ${calculations.costPerReturn?.toFixed(2) || 'N/A'}</div>
              <div>Total Expenses: ${calculations.totalExpenses?.toLocaleString() || 'N/A'}</div>
            </div>
            
            <details>
              <summary style={{ cursor: 'pointer', color: '#9ca3af', fontSize: 10 }}>
                Show Full Calculation Data
              </summary>
              <pre style={{ fontSize: 9, overflow: 'auto', background: '#111827', padding: 8, borderRadius: 4, marginTop: 8 }}>
                {JSON.stringify(calculations, null, 2)}
              </pre>
            </details>
          </div>
        ) : (
          <div style={{ color: '#9ca3af' }}>No calculation data available</div>
        )}
      </div>
    )
  }

  const renderStateView = () => (
    <div>
      <div style={{ fontWeight: 'bold', marginBottom: 8, color: '#ef4444' }}>App State</div>
      {appState ? (
        <pre style={{ fontSize: 10, overflow: 'auto', background: '#111827', padding: 8, borderRadius: 4 }}>
          {JSON.stringify(appState, null, 2)}
        </pre>
      ) : (
        <div style={{ color: '#9ca3af' }}>No state data available</div>
      )}
    </div>
  )

  const renderPerformanceView = () => (
    <div>
      <div style={{ fontWeight: 'bold', marginBottom: 8, color: '#06b6d4' }}>Performance</div>
      <div>Modules Loaded: {document.querySelectorAll('script').length}</div>
      <div>DOM Nodes: {document.querySelectorAll('*').length}</div>
      <div>Memory: {(performance as any).memory ? `${Math.round((performance as any).memory.usedJSHeapSize / 1024 / 1024)}MB` : 'N/A'}</div>
      <div style={{ marginTop: 12 }}>
        <button 
          style={buttonStyle} 
          onClick={() => console.log('Performance timing:', performance.timing)}
        >
          Log Performance Timing
        </button>
      </div>
    </div>
  )

  const renderThresholdsView = () => {
    const [expandedSection, setExpandedSection] = useState<string | null>('kpi')

    // Common styles
    const inputStyle: React.CSSProperties = {
      width: '70px',
      padding: '3px 5px',
      background: '#374151',
      border: '1px solid #4b5563',
      borderRadius: '3px',
      color: '#f9fafb',
      fontSize: '10px',
      fontFamily: 'monospace'
    }

    const labelStyle: React.CSSProperties = {
      display: 'block',
      marginBottom: '3px',
      fontSize: '10px',
      color: '#d1d5db'
    }

    const sectionStyle: React.CSSProperties = {
      marginBottom: '16px',
      background: '#1f2937',
      borderRadius: '6px',
      border: '1px solid #374151'
    }

    const headerStyle: React.CSSProperties = {
      padding: '8px 12px',
      background: '#111827',
      borderRadius: '6px 6px 0 0',
      cursor: 'pointer',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      fontSize: '11px',
      fontWeight: 'bold'
    }

    const contentStyle: React.CSSProperties = {
      padding: '12px',
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: '8px',
      fontSize: '10px'
    }

    const buttonStyle: React.CSSProperties = {
      padding: '4px 8px',
      background: '#374151',
      border: '1px solid #4b5563',
      borderRadius: '4px',
      color: '#f9fafb',
      cursor: 'pointer',
      fontSize: '10px',
      fontFamily: 'monospace'
    }

    // Section toggle
    const toggleSection = (section: string) => {
      setExpandedSection(expandedSection === section ? null : section)
    }

    return (
      <div>
        <div style={{ fontWeight: 'bold', marginBottom: 16, color: '#10b981' }}>🎯 Advanced Controls</div>
        <div style={{ fontSize: 10, color: '#9ca3af', marginBottom: 16 }}>
          💡 <strong>Power User Controls:</strong> Modify thresholds, presets, and defaults to test different scenarios.
        </div>

        {/* KPI Thresholds Section */}
        <div style={sectionStyle}>
          <div 
            style={{ ...headerStyle, color: '#fbbf24' }}
            onClick={() => toggleSection('kpi')}
          >
            <span>🎯 KPI Color Thresholds</span>
            <span>{expandedSection === 'kpi' ? '▼' : '▶'}</span>
          </div>
          {expandedSection === 'kpi' && thresholds && onUpdateThresholds && (
            <div style={contentStyle}>
              <div>
                <label style={labelStyle}>Cost/Return Green ≤ $</label>
                <input
                  type="number"
                  step="0.1"
                  value={thresholds.cprGreen}
                  onChange={(e) => onUpdateThresholds({
                    ...thresholds,
                    cprGreen: parseFloat(e.target.value) || 0
                  })}
                  placeholder="15.0"
                  aria-label="Cost per Return Green threshold"
                  style={inputStyle}
                />
              </div>
              <div>
                <label style={labelStyle}>Cost/Return Yellow ≤ $</label>
                <input
                  type="number"
                  step="0.1"
                  value={thresholds.cprYellow}
                  onChange={(e) => onUpdateThresholds({
                    ...thresholds,
                    cprYellow: parseFloat(e.target.value) || 0
                  })}
                  placeholder="20.0"
                  aria-label="Cost per Return Yellow threshold"
                  style={inputStyle}
                />
              </div>
              <div>
                <label style={labelStyle}>Net Margin Green ≥ %</label>
                <input
                  type="number"
                  step="0.1"
                  value={thresholds.nimGreen}
                  onChange={(e) => onUpdateThresholds({
                    ...thresholds,
                    nimGreen: parseFloat(e.target.value) || 0
                  })}
                  placeholder="25.0"
                  aria-label="Net Income Margin Green threshold"
                  style={inputStyle}
                />
              </div>
              <div>
                <label style={labelStyle}>Net Margin Yellow ≥ %</label>
                <input
                  type="number"
                  step="0.1"
                  value={thresholds.nimYellow}
                  onChange={(e) => onUpdateThresholds({
                    ...thresholds,
                    nimYellow: parseFloat(e.target.value) || 0
                  })}
                  placeholder="15.0"
                  aria-label="Net Income Margin Yellow threshold"
                  style={inputStyle}
                />
              </div>
              <div style={{ gridColumn: '1 / -1' }}>
                <label style={labelStyle}>Net Income Warning ≤ $</label>
                <input
                  type="number"
                  step="100"
                  value={thresholds.netIncomeWarn}
                  onChange={(e) => onUpdateThresholds({
                    ...thresholds,
                    netIncomeWarn: parseFloat(e.target.value) || 0
                  })}
                  placeholder="-5000"
                  aria-label="Net Income Warning threshold"
                  style={inputStyle}
                />
                <div style={{ fontSize: 9, color: '#9ca3af', marginTop: 2 }}>
                  Usually negative (e.g., -5000)
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Scenario Presets Section */}
        <div style={sectionStyle}>
          <div 
            style={{ ...headerStyle, color: '#06b6d4' }}
            onClick={() => toggleSection('presets')}
          >
            <span>📊 Scenario Presets</span>
            <span>{expandedSection === 'presets' ? '▼' : '▶'}</span>
          </div>
          {expandedSection === 'presets' && (
            <div style={{ padding: '12px' }}>
              <div style={{ marginBottom: 12, fontSize: 10, color: '#9ca3af' }}>
                Quick-apply Good/Better/Best scenarios to see different performance levels.
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '6px', marginBottom: 12 }}>
                {(['Good', 'Better', 'Best'] as const).map(scenario => (
                  <button
                    key={scenario}
                    style={{
                      ...buttonStyle,
                      background: scenario === 'Good' ? '#065f46' : 
                                 scenario === 'Better' ? '#1e40af' : '#7c2d12'
                    }}
                    onClick={() => onApplyPreset && onApplyPreset(presets[scenario])}
                  >
                    {scenario}
                  </button>
                ))}
              </div>
              <div style={{ fontSize: 9, color: '#9ca3af' }}>
                <strong>Good:</strong> ANF $130, 1680 returns, 26% salaries<br/>
                <strong>Better:</strong> ANF $135, 1840 returns, 24% salaries<br/>
                <strong>Best:</strong> ANF $140, 2000 returns, 22% salaries
              </div>
            </div>
          )}
        </div>

        {/* Expense Defaults Section */}
        <div style={sectionStyle}>
          <div 
            style={{ ...headerStyle, color: '#10b981' }}
            onClick={() => toggleSection('expenses')}
          >
            <span>💼 Expense Defaults</span>
            <span>{expandedSection === 'expenses' ? '▼' : '▶'}</span>
          </div>
          {expandedSection === 'expenses' && appState && (
            <div style={{ padding: '12px' }}>
              <div style={{ marginBottom: 12, fontSize: 10, color: '#9ca3af' }}>
                Current expense values. Changes update the main UI instantly.
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px', fontSize: 9 }}>
                <div>
                  <strong>Personnel</strong>
                  <div>Salaries: {appState.salariesPct}%</div>
                  <div>Emp. Deductions: {appState.empDeductionsPct}%</div>
                </div>
                <div>
                  <strong>Facility</strong>
                  <div>Rent: {appState.rentPct}%</div>
                  <div>Phone: ${appState.telephoneAmt}</div>
                  <div>Utilities: ${appState.utilitiesAmt}</div>
                </div>
                <div>
                  <strong>Operations</strong>
                  <div>Supplies: {appState.suppliesPct}%</div>
                  <div>Insurance: ${appState.insuranceAmt}</div>
                  <div>Postage: ${appState.postageAmt}</div>
                </div>
                <div>
                  <strong>Franchise</strong>
                  <div>Royalties: {appState.royaltiesPct}%</div>
                  <div>Adv. Roy: {appState.advRoyaltiesPct}%</div>
                  <div>Misc: {appState.miscPct}%</div>
                </div>
              </div>
              <div style={{ marginTop: 12 }}>
                <button
                  style={buttonStyle}
                  onClick={() => onResetDefaults && onResetDefaults()}
                >
                  🔄 Reset All to Factory Defaults
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Help Section */}
        <div style={{ marginTop: 16, padding: '8px', background: '#0f172a', borderRadius: '4px', fontSize: 9, color: '#94a3b8' }}>
          <strong>💡 Usage Tips:</strong>
          <br />• <strong>KPI Thresholds:</strong> Lower = easier green status
          <br />• <strong>Scenarios:</strong> Test Good/Better/Best performance levels  
          <br />• <strong>Expenses:</strong> View current values, reset if needed
          <br />• All changes auto-save and update UI instantly
        </div>
      </div>
    )
  }

  const renderContent = () => {
    switch (activeView) {
      case 'storage': return renderStorageView()
      case 'calculations': return renderCalculationsView()
      case 'state': return renderStateView()
      case 'performance': return renderPerformanceView()
      case 'thresholds': return renderThresholdsView()
      case 'suggestions': return renderSuggestionsView()
      default: return renderStorageView()
    }
  }

  const renderSuggestionsView = () => {
    const region = appState?.region || 'US'
    
    return (
      <SuggestionManager 
        region={region}
        onProfileUpdate={(profileKey, profile) => {
          console.log('🎯 DEBUG: Updating suggestion profile', { profileKey, profile })
          // Could save to localStorage or send to server in the future
        }}
      />
    )
  }

  return (
    <div style={sidebarStyle}>
      <div style={headerStyle}>
        <div style={{ fontWeight: 'bold', color: '#f59e0b' }}>🐛 Debug Panel</div>
        <button 
          onClick={onClose}
          style={{ 
            background: 'none', 
            border: 'none', 
            color: '#9ca3af', 
            cursor: 'pointer',
            fontSize: 16,
          }}
        >
          ✕
        </button>
      </div>

      <div style={{ 
        padding: '8px 16px', 
        fontSize: 11, 
        backgroundColor: '#0f172a', 
        borderBottom: '1px solid #374151',
        color: '#94a3b8'
      }}>
        💡 <strong>Help:</strong> Troubleshoot issues, check data, export for support
      </div>

      <div style={tabsStyle}>
        <button 
          style={tabStyle(activeView === 'storage')} 
          onClick={() => setActiveView('storage')}
          title="💾 Data Storage - Check if changes are saving properly"
        >
          💾 Storage
        </button>
        <button 
          style={tabStyle(activeView === 'calculations')} 
          onClick={() => setActiveView('calculations')}
          title="🧮 Calculations - See how your P&L numbers are computed"
        >
          🧮 Calc
        </button>
        <button 
          style={tabStyle(activeView === 'state')} 
          onClick={() => setActiveView('state')}
          title="📊 Current Values - All your input fields and settings"
        >
          📊 State
        </button>
        <button 
          style={tabStyle(activeView === 'performance')} 
          onClick={() => setActiveView('performance')}
          title="⚡ System Status - App performance and loading states"
        >
          ⚡ Perf
        </button>
        <button 
          style={tabStyle(activeView === 'thresholds')} 
          onClick={() => setActiveView('thresholds')}
          title="🎯 Thresholds - Adjust KPI thresholds, scenario defaults, and expense defaults"
        >
          🎯 Thresholds
        </button>
        <button 
          style={tabStyle(activeView === 'suggestions')} 
          onClick={() => setActiveView('suggestions')}
          title="💡 Suggestion Profiles - Manage contextual suggestions and examples"
        >
          💡 Suggest
        </button>
      </div>

      <div style={contentStyle}>
        {renderContent()}
      </div>
    </div>
  )
}

// react-app-reference/react-app-reference/src/app/components/debug-system/debug-sidebar.component.ts
// debug-sidebar.component.ts - Debug sidebar component
// Professional debug interface that doesn't interfere with main UI

import { Component, Input, Output, EventEmitter, OnInit, OnChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { CalculationResults } from '../../models/calculation.models';
import { InputsPanelData } from '../../models/expense.models';

export interface Thresholds {
  cprGreen: number;
  cprYellow: number;
  nimGreen: number;
  nimYellow: number;
  netIncomeWarn: number;
}

export type DebugView = 'storage' | 'calculations' | 'state' | 'performance' | 'thresholds' | 'regression';

@Component({
  selector: 'app-debug-sidebar',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './debug-sidebar.component.html',
  styleUrls: ['./debug-sidebar.component.scss']
})
export class DebugSidebarComponent implements OnInit, OnChanges {
  @Input() isOpen: boolean = false;
  @Input() storageKey: string = '';
  @Input() origin: string = '';
  @Input() appVersion: string = '1.0.0';
  @Input() isReady: boolean = false;
  @Input() isHydrating: boolean = false;
  @Input() savedAt: string = '(never)';
  @Input() calculations?: CalculationResults;
  @Input() appState?: InputsPanelData;
  @Input() thresholds?: Thresholds;
  @Input() testResults: any[] = [];

  @Output() close = new EventEmitter<void>();
  @Output() saveNow = new EventEmitter<void>();
  @Output() dumpStorage = new EventEmitter<void>();
  @Output() copyJSON = new EventEmitter<void>();
  @Output() clearStorage = new EventEmitter<void>();
  @Output() showWizard = new EventEmitter<void>();
  @Output() thresholdsChange = new EventEmitter<Thresholds>();
  @Output() runRegressionTests = new EventEmitter<void>();
  @Output() exportTestResults = new EventEmitter<void>();

  activeView: DebugView = 'storage';
  expandedSection: string | null = 'kpi';
  debugViews: DebugView[] = ['storage', 'calculations', 'state', 'performance', 'thresholds', 'regression'];

  ngOnInit(): void {
    // Initialize component
  }

  ngOnChanges(): void {
    // Handle input changes
  }

  onClose(): void {
    this.close.emit();
  }

  onSaveNow(): void {
    this.saveNow.emit();
  }

  onDumpStorage(): void {
    this.dumpStorage.emit();
  }

  onCopyJSON(): void {
    this.copyJSON.emit();
  }

  onClearStorage(): void {
    this.clearStorage.emit();
  }

  onShowWizard(): void {
    this.showWizard.emit();
  }

  onRunRegressionTests(): void {
    this.runRegressionTests.emit();
  }

  onExportTestResults(): void {
    this.exportTestResults.emit();
  }

  onThresholdsChange(thresholds: Thresholds): void {
    this.thresholdsChange.emit(thresholds);
  }

  setActiveView(view: DebugView): void {
    this.activeView = view;
  }

  toggleSection(section: string): void {
    this.expandedSection = this.expandedSection === section ? null : section;
  }

  // Helper methods for template display
  getCostPerReturnDisplay(): string {
    return this.calculations?.costPerReturn?.toFixed(2) || 'N/A';
  }

  getCprStatusDisplay(): string {
    return this.calculations?.cprStatus?.toUpperCase() || 'N/A';
  }

  getNetMarginDisplay(): string {
    return this.calculations?.netMarginPct?.toFixed(1) || 'N/A';
  }

  getNimStatusDisplay(): string {
    return this.calculations?.nimStatus?.toUpperCase() || 'N/A';
  }

  getNetIncomeDisplay(): string {
    return this.calculations?.netIncome?.toLocaleString() || 'N/A';
  }

  getNetMarginPctDisplay(): string {
    return this.calculations?.netMarginPct?.toFixed(1) || 'N/A';
  }

  getTotalExpensesDisplay(): string {
    return this.calculations?.totalExpenses?.toLocaleString() || 'N/A';
  }

  getRevenuePerReturn(): number {
    if (!this.calculations || !this.appState) return 0;
    return this.calculations.totalRevenue > 0 && this.appState.taxPrepReturns > 0 
      ? this.calculations.totalRevenue / this.appState.taxPrepReturns 
      : 0;
  }

  getCprGreenMin(): number {
    return this.getRevenuePerReturn() * 0.745; // 74.5%
  }

  getCprGreenMax(): number {
    return this.getRevenuePerReturn() * 0.775; // 77.5%
  }

  getNimGreenMin(): number {
    return 22.5;
  }

  getNimGreenMax(): number {
    return 25.5;
  }

  getStatusStyle(status: string | undefined): any {
    const colors = {
      green: '#10b981',
      yellow: '#f59e0b',
      red: '#ef4444'
    };
    return {
      color: status ? colors[status as keyof typeof colors] || '#9ca3af' : '#9ca3af',
      fontWeight: 'bold'
    };
  }

  getButtonStyle(): any {
    return {
      padding: '6px 12px',
      margin: '4px 0',
      background: '#374151',
      color: '#f9fafb',
      border: 'none',
      borderRadius: '4px',
      cursor: 'pointer',
      fontSize: '11px',
      transition: 'background 0.2s ease'
    };
  }

  getTestStatusStyle(passed: boolean): any {
    return {
      color: passed ? '#10b981' : '#ef4444',
      fontWeight: 'bold'
    };
  }

  getMemoryUsage(): string {
    const memory = (performance as any).memory;
    return memory ? `${Math.round(memory.usedJSHeapSize / 1024 / 1024)}MB` : 'N/A';
  }

  getTabLabel(view: DebugView): string {
    const labels = {
      storage: '💾 Storage',
      calculations: '🧮 Calc',
      state: '📊 State',
      performance: '⚡ Perf',
      thresholds: '🎯 Thresholds',
      regression: '🧪 Tests'
    };
    return labels[view];
  }

  getTabTitle(view: DebugView): string {
    const titles = {
      storage: '💾 Data Storage - Check if changes are saving properly',
      calculations: '🧮 Calculations - See how your P&L numbers are computed',
      state: '📊 Current Values - All your input fields and settings',
      performance: '⚡ System Status - App performance and loading states',
      thresholds: '🎯 Thresholds - Adjust KPI thresholds and defaults',
      regression: '🧪 Regression Tests - Compare Angular vs React calculations'
    };
    return titles[view];
  }

  getModuleCount(): number {
    return document.querySelectorAll('script').length;
  }

  getDOMNodeCount(): number {
    return document.querySelectorAll('*').length;
  }

  logPerformanceTiming(): void {
    console.log('Performance timing:', performance.timing);
  }

  updateThreshold(property: keyof Thresholds, event: Event): void {
    if (!this.thresholds) return;
    
    const target = event.target as HTMLInputElement;
    const value = parseFloat(target.value) || 0;
    
    const updatedThresholds = {
      ...this.thresholds,
      [property]: value
    };
    
    this.onThresholdsChange(updatedThresholds);
  }
}
<!-- Debug Sidebar Template -->
<div class="debug-sidebar" [class.open]="isOpen">
  <!-- Header -->
  <div class="debug-header">
    <div class="debug-title">🐛 Debug Panel</div>
    <button class="close-button" (click)="onClose()" title="Close Debug Panel">
      ✕
    </button>
  </div>

  <!-- Help Text -->
  <div class="debug-help">
    💡 <strong>Help:</strong> Troubleshoot issues, check data, export for support
  </div>

  <!-- Tabs -->
  <div class="debug-tabs">
    <button 
      *ngFor="let view of debugViews"
      class="debug-tab" 
      [class.active]="activeView === view"
      (click)="setActiveView(view)"
      [title]="getTabTitle(view)">
      {{ getTabLabel(view) }}
    </button>
  </div>

  <!-- Content -->
  <div class="debug-content">
    <!-- Storage View -->
    <div *ngIf="activeView === 'storage'" class="debug-view">
      <div class="info-block">
        <div class="info-text">
          📝 <strong>What is this?</strong> Your data is automatically saved to your browser's local storage. 
          This shows the status of your saved data and lets you manage it.
        </div>
      </div>

      <div class="section">
        <div class="section-title">💾 Storage Status</div>
        <div class="info-item">
          <div class="info-label">Storage Key:</div>
          <div class="info-value">{{ storageKey }}</div>
        </div>
        <div class="info-item">
          <div class="info-label">App Version:</div>
          <div class="info-value">{{ appVersion }}</div>
        </div>
        <div class="info-item">
          <div class="info-label">System Status:</div>
          <div class="info-value">
            Ready: {{ isReady ? '✅' : '❌' }} | Loading: {{ isHydrating ? '🔄' : '✅' }}
          </div>
        </div>
        <div class="info-item">
          <div class="info-label">Last Auto-Save:</div>
          <div class="info-value" [class.error]="savedAt === '(never)'">{{ savedAt }}</div>
        </div>
      </div>

      <div class="section">
        <div class="section-title">🔧 Quick Actions</div>
        <div class="button-grid">
          <button class="action-button" (click)="onSaveNow()" title="Force save your current data now">
            💾 Save Now
          </button>
          <button class="action-button" (click)="onDumpStorage()" title="Print all saved data to browser console for debugging">
            🖥️ Dump to Console
          </button>
          <button class="action-button" (click)="onCopyJSON()" title="Copy all your data as JSON to clipboard">
            📋 Copy JSON
          </button>
          <button class="action-button" (click)="onShowWizard()" title="Restart the setup wizard">
            🧙‍♂️ Reopen Wizard
          </button>
          <button class="action-button danger" (click)="onClearStorage()" title="⚠️ WARNING: This will delete ALL your saved data!">
            🗑️ Clear All Data
          </button>
        </div>
      </div>
    </div>

    <!-- Calculations View -->
    <div *ngIf="activeView === 'calculations'" class="debug-view">
      <div class="info-block">
        <div class="info-text">
          🧮 <strong>What is this?</strong> Shows how your P&L numbers are calculated from your inputs. 
          Use this to verify calculations or troubleshoot unexpected results.
        </div>
      </div>

      <!-- KPI Strategic Analysis -->
      <div *ngIf="calculations && appState" class="kpi-analysis">
        <div class="analysis-title">🎯 KPI Strategic Analysis</div>
        <div class="analysis-content">
          <div class="analysis-item">
            <strong>Revenue per Return:</strong> ${{ getRevenuePerReturn() | number:'1.2-2' }}
          </div>
          <div class="analysis-item">
            <strong>Cost/Return Strategic Range:</strong> ${{ getCprGreenMin() | number:'1.2-2' }} - ${{ getCprGreenMax() | number:'1.2-2' }} (GREEN)
          </div>
          <div class="analysis-item">
            <strong>Actual Cost/Return:</strong> ${{ getCostPerReturnDisplay() }}
            <span [style]="getStatusStyle(calculations.cprStatus)">
              ({{ getCprStatusDisplay() }})
            </span>
          </div>
          <div class="analysis-item">
            <strong>Net Margin Strategic Range:</strong> {{ getNimGreenMin() }}% - {{ getNimGreenMax() }}% (GREEN)
          </div>
          <div class="analysis-item">
            <strong>Actual Net Margin:</strong> {{ getNetMarginDisplay() }}%
            <span [style]="getStatusStyle(calculations.nimStatus)">
              ({{ getNimStatusDisplay() }})
            </span>
          </div>
          <div class="analysis-tip">
            💡 <strong>Expected Result:</strong> When Page 2 shows green, Dashboard should show all green KPIs
          </div>
        </div>
      </div>

      <div class="section">
        <div class="section-title">📊 Current Calculations</div>
        <div *ngIf="calculations; else noCalculations">
          <div class="calculation-summary">
            <div class="summary-title">Key Results:</div>
            <div>Net Income: ${{ getNetIncomeDisplay() }}</div>
            <div>Net Margin: {{ getNetMarginPctDisplay() }}%</div>
            <div>Cost/Return: ${{ getCostPerReturnDisplay() }}</div>
            <div>Total Expenses: ${{ getTotalExpensesDisplay() }}</div>
          </div>
          
          <details>
            <summary class="details-summary">Show Full Calculation Data</summary>
            <pre class="calculation-data">{{ calculations | json }}</pre>
          </details>
        </div>
        <ng-template #noCalculations>
          <div class="no-data">No calculation data available</div>
        </ng-template>
      </div>
    </div>

    <!-- State View -->
    <div *ngIf="activeView === 'state'" class="debug-view">
      <div class="section">
        <div class="section-title">App State</div>
        <div *ngIf="appState; else noState">
          <pre class="state-data">{{ appState | json }}</pre>
        </div>
        <ng-template #noState>
          <div class="no-data">No state data available</div>
        </ng-template>
      </div>
    </div>

    <!-- Performance View -->
    <div *ngIf="activeView === 'performance'" class="debug-view">
      <div class="section">
        <div class="section-title">Performance</div>
        <div class="performance-item">Modules Loaded: {{ getModuleCount() }}</div>
        <div class="performance-item">DOM Nodes: {{ getDOMNodeCount() }}</div>
        <div class="performance-item">Memory: {{ getMemoryUsage() }}</div>
        <div class="performance-actions">
          <button class="action-button" (click)="logPerformanceTiming()">
            Log Performance Timing
          </button>
        </div>
      </div>
    </div>

    <!-- Thresholds View -->
    <div *ngIf="activeView === 'thresholds'" class="debug-view">
      <div class="section">
        <div class="section-title">🎯 Advanced Controls</div>
        <div class="info-text">
          💡 <strong>Power User Controls:</strong> Modify thresholds, presets, and defaults to test different scenarios.
        </div>

        <!-- KPI Thresholds Section -->
        <div class="threshold-section">
          <div class="threshold-header" (click)="toggleSection('kpi')">
            <span>🎯 KPI Color Thresholds</span>
            <span>{{ expandedSection === 'kpi' ? '▼' : '▶' }}</span>
          </div>
          <div *ngIf="expandedSection === 'kpi' && thresholds" class="threshold-content">
            <div class="threshold-grid">
              <div class="threshold-item">
                <label>Cost/Return Green ≤ $</label>
                <input
                  type="number"
                  step="0.1"
                  [value]="thresholds.cprGreen"
                  (input)="updateThreshold('cprGreen', $event)"
                  placeholder="15.0"
                  class="threshold-input">
              </div>
              <div class="threshold-item">
                <label>Cost/Return Yellow ≤ $</label>
                <input
                  type="number"
                  step="0.1"
                  [value]="thresholds.cprYellow"
                  (input)="updateThreshold('cprYellow', $event)"
                  placeholder="20.0"
                  class="threshold-input">
              </div>
              <div class="threshold-item">
                <label>Net Margin Green ≥ %</label>
                <input
                  type="number"
                  step="0.1"
                  [value]="thresholds.nimGreen"
                  (input)="updateThreshold('nimGreen', $event)"
                  placeholder="25.0"
                  class="threshold-input">
              </div>
              <div class="threshold-item">
                <label>Net Margin Yellow ≥ %</label>
                <input
                  type="number"
                  step="0.1"
                  [value]="thresholds.nimYellow"
                  (input)="updateThreshold('nimYellow', $event)"
                  placeholder="15.0"
                  class="threshold-input">
              </div>
              <div class="threshold-item full-width">
                <label>Net Income Warning ≤ $</label>
                <input
                  type="number"
                  step="100"
                  [value]="thresholds.netIncomeWarn"
                  (input)="updateThreshold('netIncomeWarn', $event)"
                  placeholder="-5000"
                  class="threshold-input">
                <div class="threshold-help">Usually negative (e.g., -5000)</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Regression Testing View -->
    <div *ngIf="activeView === 'regression'" class="debug-view">
      <div class="section">
        <div class="section-title">🧪 Regression Testing</div>
        <div class="info-text">
          💡 <strong>Compare Angular vs React:</strong> Run tests to ensure calculations match between Angular and React versions.
        </div>

        <div class="test-actions">
          <button class="action-button" (click)="onRunRegressionTests()">
            🧪 Run Regression Tests
          </button>
          <button class="action-button" (click)="onExportTestResults()">
            📋 Export Test Results
          </button>
        </div>

        <div *ngIf="testResults && testResults.length > 0" class="test-results">
          <div class="results-title">Test Results</div>
          <div *ngFor="let result of testResults" class="test-result">
            <div class="test-header">
              <span class="test-name">{{ result.testName }}</span>
              <span [style]="getTestStatusStyle(result.passed)">
                {{ result.passed ? '✅ PASS' : '❌ FAIL' }}
              </span>
            </div>
            <div *ngIf="result.differences && result.differences.length > 0" class="test-differences">
              <div *ngFor="let diff of result.differences" class="difference">{{ diff }}</div>
            </div>
            <div class="test-timestamp">
              {{ result.timestamp | date:'short' }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
