// src/App.tsx
// App.tsx - Clean main application component using hooks architecture
// Dramatically simplified using custom hooks for state and logic management

import React from 'react'
import WizardShell from './components/WizardShell'
import type { WizardAnswers } from './components/WizardShell'
import Header from './components/Header'
import InputsPanel from './components/InputsPanel'
import Dashboard from './components/Dashboard/Dashboard'
import ProjectedPerformancePanel from './components/ProjectedPerformancePanel'
import DebugToggle from './components/DebugSystem/DebugToggle'
import DebugSidebar from './components/DebugSystem/DebugSidebar'
import DebugErrorBoundary from './components/DebugSystem/DebugErrorBoundary'
import Footer from './components/Footer'
import BrandWatermark from './components/BrandWatermark'
import { useAppState } from './hooks/useAppState'
import { useCalculations } from './hooks/useCalculations'
import { usePersistence } from './hooks/usePersistence'
import { usePresets } from './hooks/usePresets'
import { useBranding } from './hooks/useBranding'

export default function App() {
  // Custom hooks for clean separation of concerns
  const appState = useAppState()
  const calculations = useCalculations(appState)
  const persistence = usePersistence()
  const presets = usePresets(appState)
  const branding = useBranding(appState.region) // Apply regional branding

  // Initialize wizard state from persistence on app startup
  React.useEffect(() => {
    const wizardState = persistence.getWizardState()

    // If wizard is incomplete, show it
    if (wizardState.showWizard && !appState.showWizard) {
      console.log('🧙‍♂️ Restoring incomplete wizard session')
      appState.setShowWizard(true)
    }

    // 🔧 FIX: If wizard is completed, load and apply saved answers to app state
    if (wizardState.wizardCompleted && !wizardState.showWizard) {
      const savedAnswers = persistence.loadWizardAnswers()
      if (savedAnswers) {
        console.log('🧙‍♂️ Loading completed wizard answers on startup:', savedAnswers)
        appState.applyWizardAnswers(savedAnswers)
      } else {
        console.warn('⚠️ Wizard marked as completed but no saved answers found')
      }
    }
  }, [persistence, appState])

  // Immediate autosave on core input changes for tests that wait on storage writes
  React.useEffect(() => {
    persistence.saveBaseline(appState)
    persistence.saveNow()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [appState.region, appState.avgNetFee, appState.taxPrepReturns, appState.discountsPct])

  // Debug system state
  const [debugOpen, setDebugOpen] = React.useState(false)

  // Reset counter to force wizard remount when reset happens
  const [resetCounter, setResetCounter] = React.useState(0)

  // Wizard handlers
  const handleWizardComplete = (answers: WizardAnswers) => {
    appState.applyWizardAnswers(answers)
    persistence.saveBaseline(appState)
    persistence.saveWizardAnswers(answers) // Save wizard answers for review mode
    persistence.markWizardCompleted() // Mark wizard as completed in storage
    appState.setShowWizard(false)
    persistence.dbg('wizard: completed with answers', answers)
  }

  const handleWizardCancel = () => {
    appState.setShowWizard(false)
    persistence.dbg('wizard: cancelled')
  }

  // Reset handler - now forces wizard remount and shows wizard
  const handleReset = () => {
    persistence.dbg('ui: Reset session - forcing wizard remount')
    appState.resetToDefaults()
    localStorage.removeItem(persistence.STORAGE_KEY)
    setResetCounter(prev => prev + 1) // Force wizard remount by changing key
    appState.setShowWizard(true) // Always show wizard after reset
  }

  // 🔄 BIDIRECTIONAL FLOW: Handle dashboard changes flowing back to wizard
  const handleDashboardToWizard = (updates: any) => {
    // Load current wizard answers
    const currentAnswers = persistence.loadWizardAnswers() || {}

    // Merge dashboard changes with existing wizard answers
    const updatedAnswers = { ...currentAnswers, ...updates }

    // Save back to wizard persistence
    persistence.saveWizardAnswers(updatedAnswers)

    persistence.dbg('dashboard: Updated wizard persistence from dashboard changes', {
      updates,
      mergedAnswers: updatedAnswers
    })
  }

  // Debug panel handlers
  const handleSaveNow = () => {
    persistence.dbg('ui: Save Now')
    persistence.saveNow()
  }

  const handleDumpStorage = () => {
    persistence.dbg('ui: Dump storage')
    const env = persistence.loadEnvelope()
    console.log('ENVELOPE', env)
  }

  const handleCopyJSON = () => {
    try {
      const env = persistence.loadEnvelope()
      navigator.clipboard?.writeText(JSON.stringify(env ?? {}, null, 2))
      persistence.dbg('ui: Copied envelope to clipboard')
    } catch { }
  }

  const handleClearStorage = () => {
    persistence.dbg('ui: Clear & reset')
    localStorage.removeItem(persistence.STORAGE_KEY)
    setResetCounter(prev => prev + 1) // Force wizard remount to clear state
  }

  // Debug panel configuration
  const showDebug = true // Enable debug UI for test expectations

  const savedAt = (() => {
    try {
      const env = persistence.loadEnvelope()
      const iso = env?.meta?.savedAtISO
      return iso ? new Date(iso).toLocaleString() : '(never)'
    } catch {
      return '—'
    }
  })()

  // Main render - clean and focused
  return (
    <div style={{ display: 'flex', minHeight: '100vh' }}>
      {/* Regional Brand Watermark */}
      <BrandWatermark region={appState.region} />

      <div style={{
        flex: 1,
        transition: 'margin-right 0.3s ease',
        marginRight: debugOpen ? '350px' : '0',
        position: 'relative',
        zIndex: 1 // Ensure content is above watermark
      }}>
        <Header
          region={appState.region}
          setRegion={(newRegion) => {
            appState.setRegion(newRegion)
            // Save region change immediately to persistence
            persistence.saveBaseline({ ...appState, region: newRegion })
          }}
          onReset={handleReset}
          onShowWizard={() => appState.setShowWizard(true)}
          onShowDashboard={() => appState.setShowWizard(false)}
          onShowReports={() => {
            // Future: Navigate to reports page
            console.log('📊 Reports feature coming soon!')
            // For now, trigger export or show reports modal
          }}
          wizardCompleted={persistence.getWizardState().wizardCompleted}
          showWizard={appState.showWizard}
          currentPage={appState.showWizard ? 'wizard' : 'dashboard'}
          storeType={persistence.loadWizardAnswers()?.storeType}
        />

        {appState.showWizard ? (
          <WizardShell
            key={resetCounter} // Force remount on reset to clear wizard state
            region={appState.region}
            setRegion={(newRegion) => {
              appState.setRegion(newRegion)
              // Save region change immediately to persistence
              persistence.saveBaseline({ ...appState, region: newRegion })
            }}
            onComplete={handleWizardComplete}
            onCancel={handleWizardCancel}
            persistence={persistence} // Pass persistence for loading saved answers
          />
        ) : (
          <div className="container" style={{ display: 'grid', gridTemplateColumns: 'minmax(300px, 350px) minmax(400px, 500px) minmax(600px, 1fr)', gap: '1.5rem', alignItems: 'start' }}>
            <ProjectedPerformancePanel
              grossFees={calculations.grossFees}
              discounts={calculations.discounts}
              taxPrepIncome={calculations.taxPrepIncome}
              taxRushIncome={calculations.taxRushIncome}
              totalRevenue={calculations.totalRevenue}
              totalExpenses={calculations.totalExpenses}
              netIncome={calculations.netIncome}
              netMarginPct={calculations.netMarginPct}
              costPerReturn={calculations.costPerReturn}
              totalReturns={calculations.totalReturns}
              region={appState.region}
              lastYearRevenue={(() => {
                const answers = persistence.loadWizardAnswers()
                if (!answers) return 0

                // Calculate last year revenue from wizard data
                const lastYearReturns = answers.lastYearTaxPrepReturns || 0
                const lastYearAvgNetFee = answers.manualAvgNetFee || 0
                const grossFees = lastYearReturns * lastYearAvgNetFee
                const discounts = answers.lastYearDiscountsAmt || 0
                const otherIncome = answers.hasOtherIncome ? (answers.lastYearOtherIncome || 0) : 0

                console.log('🔍 PY Performance Revenue Calculation:', {
                  lastYearReturns,
                  lastYearAvgNetFee,
                  grossFees,
                  discounts,
                  otherIncome,
                  finalRevenue: grossFees - discounts + otherIncome
                })

                return grossFees - discounts + otherIncome
              })()}
              lastYearExpenses={(() => {
                const answers = persistence.loadWizardAnswers()
                if (!answers) return 0

                // Use lastYearExpenses if provided, otherwise estimate at 76% of revenue
                if (answers.lastYearExpenses) {
                  return answers.lastYearExpenses
                }

                // Calculate estimated expenses if not provided
                const lastYearReturns = answers.lastYearTaxPrepReturns || 0
                const lastYearAvgNetFee = answers.manualAvgNetFee || 0
                const grossFees = lastYearReturns * lastYearAvgNetFee
                const discounts = answers.lastYearDiscountsAmt || 0
                const taxPrepIncome = grossFees - discounts
                const otherIncome = answers.hasOtherIncome ? (answers.lastYearOtherIncome || 0) : 0
                const totalIncome = taxPrepIncome + otherIncome

                // Estimate expenses at 76% of total income (industry standard)
                const estimatedExpenses = Math.round(totalIncome * 0.76)

                console.log('🔍 PY Performance Expenses Calculation:', {
                  totalIncome,
                  estimatedExpenses,
                  source: 'estimated_76pct'
                })

                return estimatedExpenses
              })()}
              lastYearReturns={persistence.loadWizardAnswers()?.lastYearTaxPrepReturns || 0}
              expectedGrowthPct={persistence.loadWizardAnswers()?.expectedGrowthPct || 0}
              handlesTaxRush={(() => {
                const wizardAnswers = persistence.loadWizardAnswers()
                const result = appState.region === 'CA' && wizardAnswers?.handlesTaxRush
                console.log('🔍 TaxRush Logic Debug:', {
                  appStateRegion: appState.region,
                  wizardHandlesTaxRush: wizardAnswers?.handlesTaxRush,
                  finalResult: result
                })
                return result
              })()}
            />

            <InputsPanel
              region={appState.region}
              scenario={appState.scenario}
              setScenario={appState.setScenario}
              avgNetFee={appState.avgNetFee}
              setANF={appState.setANF}
              taxPrepReturns={appState.taxPrepReturns}
              setReturns={appState.setReturns}
              taxRushReturns={appState.taxRushReturns}
              setTaxRush={appState.setTaxRush}
              discountsPct={appState.discountsPct}
              setDisc={appState.setDisc}
              otherIncome={appState.otherIncome}
              setOtherIncome={appState.setOtherIncome}
              salariesPct={appState.salariesPct}
              setSal={appState.setSal}
              empDeductionsPct={appState.empDeductionsPct}
              setEmpDeductions={appState.setEmpDeductions}
              rentPct={appState.rentPct}
              setRent={appState.setRent}
              telephoneAmt={appState.telephoneAmt}
              setTelephone={appState.setTelephone}
              utilitiesAmt={appState.utilitiesAmt}
              setUtilities={appState.setUtilities}
              localAdvAmt={appState.localAdvAmt}
              setLocalAdv={appState.setLocalAdv}
              insuranceAmt={appState.insuranceAmt}
              setInsurance={appState.setInsurance}
              postageAmt={appState.postageAmt}
              setPostage={appState.setPostage}
              suppliesPct={appState.suppliesPct}
              setSup={appState.setSup}
              duesAmt={appState.duesAmt}
              setDues={appState.setDues}
              bankFeesAmt={appState.bankFeesAmt}
              setBankFees={appState.setBankFees}
              maintenanceAmt={appState.maintenanceAmt}
              setMaintenance={appState.setMaintenance}
              travelEntAmt={appState.travelEntAmt}
              setTravelEnt={appState.setTravelEnt}
              royaltiesPct={appState.royaltiesPct}
              setRoy={appState.setRoy}
              advRoyaltiesPct={appState.advRoyaltiesPct}
              setAdvRoy={appState.setAdvRoy}
              taxRushRoyaltiesPct={appState.taxRushRoyaltiesPct}
              setTaxRushRoy={appState.setTaxRushRoy}
              miscPct={appState.miscPct}
              setMisc={appState.setMisc}
              handlesTaxRush={(() => {
                const wizardAnswers = persistence.loadWizardAnswers()
                const result = appState.region === 'CA' && wizardAnswers?.handlesTaxRush
                console.log('🔍 TaxRush Logic Debug:', {
                  appStateRegion: appState.region,
                  wizardHandlesTaxRush: wizardAnswers?.handlesTaxRush,
                  finalResult: result
                })
                return result
              })()}
              hasOtherIncome={persistence.loadWizardAnswers()?.hasOtherIncome}
              onSaveToWizard={handleDashboardToWizard}
            />

            <Dashboard
              results={calculations}
              hasOtherIncome={persistence.loadWizardAnswers()?.hasOtherIncome}
            />
          </div>
        )}

        <Footer
          onNavigate={(page) => {
            switch (page) {
              case 'wizard':
                appState.setShowWizard(true)
                break
              case 'dashboard':
                if (persistence.getWizardState().wizardCompleted) {
                  appState.setShowWizard(false)
                }
                break
              case 'pro-tips':
                // Future: Open Pro-Tips modal/panel
                console.log('🔮 Pro-Tips feature coming soon!')
                break
              case 'practice':
                // Future: Open Practice Problems module
                console.log('🎯 Practice Problems feature coming soon!')
                break
              case 'export':
                // Future: Export current state to PDF/Excel
                console.log('📄 Export functionality coming soon!')
                break
              case 'settings':
              case 'reports':
                // Placeholder for future navigation
                console.log(`Navigate to ${page}`)
                break
            }
          }}
          showWizard={appState.showWizard}
          wizardCompleted={persistence.getWizardState().wizardCompleted}
          currentPage={appState.showWizard ? 'wizard' : 'dashboard'}
        />
      </div>

      <DebugToggle
        key={`debug-${appState.region}`}
        show={showDebug}
        isOpen={debugOpen}
        onToggle={() => setDebugOpen(!debugOpen)}
        region={appState.region}
      />

      <DebugErrorBoundary onClose={() => setDebugOpen(false)}>
        <DebugSidebar
          isOpen={debugOpen}
          onClose={() => setDebugOpen(false)}
          storageKey={persistence.STORAGE_KEY}
          origin={persistence.ORIGIN}
          appVersion={persistence.APP_VERSION}
          isReady={persistence.readyRef.current}
          isHydrating={persistence.hydratingRef.current}
          savedAt={savedAt}
          onSaveNow={handleSaveNow}
          onDumpStorage={handleDumpStorage}
          onCopyJSON={handleCopyJSON}
          onClearStorage={handleClearStorage}
          onShowWizard={() => appState.setShowWizard(true)}
          calculations={calculations}
          appState={appState}
          thresholds={appState.thresholds}
          onUpdateThresholds={appState.setThr}
          onApplyPreset={appState.applyPreset}
          onResetDefaults={appState.resetToDefaults}
        />
      </DebugErrorBoundary>
    </div>
  )
}

// react-app-reference/react-app-reference/src/app/app.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Region, WizardAnswers } from './models/wizard.models';
import { AppStateService } from './services/app-state.service';
import { CalculationService } from './services/calculation.service';
import { PersistenceService } from './services/persistence.service';
import { BrandingService } from './services/branding.service';
import { debugLog } from './utils/debug.utils';
import { HeaderComponent } from './components/header/header.component';
import { FooterComponent } from './components/footer/footer.component';
import { WizardShellComponent } from './components/wizard-shell/wizard-shell.component';
import { BrandWatermarkComponent } from './components/brand-watermark/brand-watermark.component';
import { DashboardComponent, CalculationResults } from './components/dashboard/dashboard.component';
import { InputsPanelComponent } from './components/inputs-panel/inputs-panel.component';
import { InputsPanelData } from './models/expense.models';
import { ProjectedPerformanceComponent, ProjectedPerformanceData } from './components/projected-performance/projected-performance.component';
import { DebugSystemComponent } from './components/debug-system/debug-system.component';
import { environment } from '../environments/environment';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule, 
    FormsModule, 
    HeaderComponent, 
    FooterComponent, 
    WizardShellComponent, 
    BrandWatermarkComponent, 
    DashboardComponent, 
    InputsPanelComponent, 
    ProjectedPerformanceComponent,
    ...(environment.DEBUG_TOOL_ENABLED ? [DebugSystemComponent] : [])
  ],
  template: `
    <div class="app-container">
      <!-- Regional Brand Watermark -->
      <app-brand-watermark [region]="appState.region"></app-brand-watermark>
      
      <!-- Main Content -->
      <div class="main-wrapper">
        <!-- Header -->
        <app-header
          [region]="appState.region"
          [showWizard]="appState.showWizard"
          [wizardCompleted]="persistence.getWizardState().wizardCompleted"
          [currentPage]="appState.showWizard ? 'wizard' : 'dashboard'"
          [storeType]="persistence.loadWizardAnswers()?.storeType"
          (setRegion)="onSetRegion($event)"
          (onReset)="onReset()"
          (onShowWizard)="onShowWizard()"
          (onShowDashboard)="onShowDashboard()"
          (onShowReports)="onShowReports()">
        </app-header>

        <!-- Main Content -->
        <main class="main-content">
          <div *ngIf="appState.showWizard" class="wizard-wrapper">
            <app-wizard-shell
              [region]="appState.region"
              [persistence]="persistence"
              [resetTrigger]="resetCounter"
              (setRegion)="onSetRegion($event)"
              (wizardComplete)="onWizardComplete($event)"
              (wizardCancel)="onWizardCancel()">
            </app-wizard-shell>
          </div>

          <div *ngIf="!appState.showWizard" class="dashboard-wrapper">
            <div class="dashboard-container">
              <!-- Dashboard Grid Layout -->
              <div class="dashboard-grid">
                <!-- Left Column: Inputs Panel -->
                <div class="dashboard-left">
                  <app-inputs-panel
                    [data]="inputsData"
                    (dataChange)="onInputsChange($event)">
                  </app-inputs-panel>
                </div>

                <!-- Right Column: Dashboard and Performance -->
                <div class="dashboard-right">
                  <!-- Main Dashboard -->
                  <app-dashboard
                    [results]="calculationResults"
                    [hasOtherIncome]="inputsData.hasOtherIncome || false">
                  </app-dashboard>

                  <!-- Projected Performance Panel -->
                  <app-projected-performance
                    [data]="projectedPerformanceData">
                  </app-projected-performance>
                </div>
              </div>
            </div>
          </div>
        </main>

        <!-- Footer -->
        <app-footer
          [showWizard]="appState.showWizard"
          [wizardCompleted]="persistence.getWizardState().wizardCompleted"
          [currentPage]="appState.showWizard ? 'wizard' : 'dashboard'"
          (onNavigate)="onNavigate($event)">
        </app-footer>
      </div>

      <!-- Debug System (dev-only) -->
      <app-debug-system
        *ngIf="debugEnabled"
        [showDebugToggle]="true"
        [region]="appState.region"
        [calculations]="calculationResults"
        [appState]="inputsData"
        (saveNow)="onDebugSaveNow()"
        (dumpStorage)="onDebugDumpStorage()"
        (copyJSON)="onDebugCopyJSON()"
        (clearStorage)="onDebugClearStorage()"
        (showWizard)="onShowWizard()"
        (thresholdsChange)="onDebugThresholdsChange($event)">
      </app-debug-system>
    </div>
  `,
  styles: [`
    .app-container {
      min-height: 100vh;
      background: #f8fafc;
      display: flex;
    }

    .main-wrapper {
      flex: 1;
      position: relative;
      z-index: 1; /* Ensure content is above watermark */
    }

    .main-content {
      padding: 2rem 0;
    }

    .wizard-wrapper,
    .dashboard-wrapper {
      max-width: 1200px;
      margin: 0 auto;
      padding: 0 2rem;
    }

    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 0 1rem;
    }

    .responsive-grid {
      display: grid;
      grid-template-columns: 1fr;
      gap: 2rem;
    }

    .dashboard-container {
      max-width: 1400px;
      margin: 0 auto;
      padding: 0 2rem;
    }

    .dashboard-grid {
      display: grid;
      grid-template-columns: 420px 1fr;
      gap: 2rem;
      align-items: start;
    }

    .dashboard-left {
      position: sticky;
      top: 2rem;
    }

    .dashboard-right {
      display: flex;
      flex-direction: column;
      gap: 2rem;
    }

    @media (max-width: 1200px) {
      .dashboard-grid {
        grid-template-columns: 1fr;
        gap: 2rem;
      }
      
      .dashboard-left {
        position: static;
      }
    }

    @media (max-width: 768px) {
      .wizard-wrapper,
      .dashboard-wrapper {
        padding: 0 1rem;
      }
      
      .dashboard-container {
        padding: 0 1rem;
      }
    }
  `]
})
export class AppComponent implements OnInit {
  appState: any = { region: 'US', showWizard: false };
  
  // Debug system visibility controlled by environment flag
  get debugEnabled(): boolean {
    return environment.DEBUG_TOOL_ENABLED;
  }
  resetCounter: number = 0;
  
  // Dashboard data
  inputsData: InputsPanelData = {
    region: 'US',
    scenario: 'Custom',
    avgNetFee: 125,
    taxPrepReturns: 1600,
    taxRushReturns: 0,
    discountsPct: 3,
    otherIncome: 0,
    salariesPct: 25,
    empDeductionsPct: 15,
    rentPct: 8,
    telephoneAmt: 200,
    utilitiesAmt: 300,
    localAdvAmt: 500,
    insuranceAmt: 200,
    postageAmt: 100,
    suppliesPct: 2,
    duesAmt: 150,
    bankFeesAmt: 100,
    maintenanceAmt: 200,
    travelEntAmt: 300,
    royaltiesPct: 8,
    advRoyaltiesPct: 2,
    taxRushRoyaltiesPct: 3,
    miscPct: 1,
    handlesTaxRush: false,
    hasOtherIncome: false
  };
  
  calculationResults: CalculationResults = {
    netIncome: 0,
    netMarginPct: 0,
    costPerReturn: 0,
    grossFees: 0,
    discounts: 0,
    taxPrepIncome: 0,
    taxRushIncome: 0,
    otherIncome: 0,
    totalRevenue: 0,
    totalExpenses: 0,
    totalReturns: 0,
    salaries: 0,
    empDeductions: 0,
    rent: 0,
    telephone: 0,
    utilities: 0,
    localAdv: 0,
    insurance: 0,
    postage: 0,
    supplies: 0,
    dues: 0,
    bankFees: 0,
    maintenance: 0,
    travelEnt: 0,
    royalties: 0,
    advRoyalties: 0,
    taxRushRoyalties: 0,
    misc: 0
  };
  
  projectedPerformanceData: ProjectedPerformanceData = {
    grossFees: 0,
    discounts: 0,
    taxPrepIncome: 0,
    taxRushIncome: 0,
    totalRevenue: 0,
    totalExpenses: 0,
    netIncome: 0,
    netMarginPct: 0,
    costPerReturn: 0,
    totalReturns: 0,
    region: 'US',
    lastYearRevenue: 0,
    lastYearExpenses: 0,
    lastYearReturns: 0,
    expectedGrowthPct: 0,
    handlesTaxRush: false
  };

  constructor(
    private appStateService: AppStateService,
    private calculationService: CalculationService,
    private brandingService: BrandingService,
    public persistence: PersistenceService
  ) {}

  ngOnInit(): void {
    // Apply initial branding
    this.brandingService.applyBrand(this.appState.region || 'US');

    // Initialize dashboard data
    this.calculateDashboardResults();

    // Subscribe to app state changes
    this.appStateService.state$.subscribe(state => {
      this.appState = state;
      // Apply branding when region changes
      this.brandingService.applyBrand(state.region);
      // Recalculate when state changes
      this.calculationService.calculateResults(state);
    });

    // Initialize from persistence
    const wizardState = this.persistence.getWizardState();
    if (wizardState.showWizard && !this.appState.showWizard) {
      console.log('🧙‍♂️ Restoring incomplete wizard session');
      this.appStateService.setShowWizard(true);
    }

    if (wizardState.wizardCompleted && !wizardState.showWizard) {
      const savedAnswers = this.persistence.loadWizardAnswers();
      if (savedAnswers) {
        console.log('🧙‍♂️ Loading completed wizard answers on startup:', savedAnswers);
        this.appStateService.applyWizardAnswers(savedAnswers);
        this.initializeDashboardFromWizard(savedAnswers);
      }
    }
  }

  onSetRegion(region: Region): void {
    this.appStateService.setRegion(region);
    this.persistence.saveBaseline(this.appStateService.currentState);
  }

  onReset(): void {
    console.log('🔄 Reset session');
    this.appStateService.resetToDefaults();
    this.persistence.clearStorage();
    this.appStateService.setShowWizard(true);
    this.resetCounter++; // Trigger wizard reset
  }

  onShowWizard(): void {
    this.appStateService.setShowWizard(true);
  }

  onShowDashboard(): void {
    this.appStateService.setShowWizard(false);
  }

  onShowReports(): void {
    console.log('📊 Reports feature coming soon!');
  }

  onWizardComplete(answers: WizardAnswers): void {
    console.log('🧙‍♂️ Wizard completed with answers:', answers);
    this.appStateService.applyWizardAnswers(answers);
    this.persistence.saveBaseline(this.appStateService.currentState);
    this.persistence.saveWizardAnswers(answers);
    this.persistence.markWizardCompleted();
    this.appStateService.setShowWizard(false);
    
    // Initialize dashboard data from wizard answers
    this.initializeDashboardFromWizard(answers);
  }

  onWizardCancel(): void {
    console.log('🧙‍♂️ Wizard cancelled');
    this.appStateService.setShowWizard(false);
  }

  onNavigate(page: string): void {
    switch(page) {
      case 'wizard':
        this.appStateService.setShowWizard(true);
        break;
      case 'dashboard':
        if (this.persistence.getWizardState().wizardCompleted) {
          this.appStateService.setShowWizard(false);
        }
        break;
      case 'pro-tips':
        console.log('🔮 Pro-Tips feature coming soon!');
        break;
      case 'practice':
        console.log('🎯 Practice Problems feature coming soon!');
        break;
      case 'export':
        console.log('📄 Export functionality coming soon!');
        break;
      case 'settings':
      case 'reports':
        console.log(`Navigate to ${page}`);
        break;
    }
  }

  // Dashboard methods
  onInputsChange(newData: InputsPanelData): void {
    this.inputsData = newData;
    this.calculateDashboardResults();
  }

  initializeDashboardFromWizard(answers: WizardAnswers): void {
    // Map wizard answers to inputs data
    this.inputsData = {
      region: answers.region,
      scenario: 'Custom',
      avgNetFee: answers.avgNetFee || 125,
      taxPrepReturns: answers.taxPrepReturns || 1600,
      taxRushReturns: answers.taxRushReturns || 0,
      discountsPct: answers.discountsPct || 3,
      otherIncome: answers.otherIncome || 0,
      salariesPct: 25,
      empDeductionsPct: 15,
      rentPct: 8,
      telephoneAmt: 200,
      utilitiesAmt: 300,
      localAdvAmt: 500,
      insuranceAmt: 200,
      postageAmt: 100,
      suppliesPct: 2,
      duesAmt: 150,
      bankFeesAmt: 100,
      maintenanceAmt: 200,
      travelEntAmt: 300,
      royaltiesPct: 8,
      advRoyaltiesPct: 2,
      taxRushRoyaltiesPct: 3,
      miscPct: 1,
      handlesTaxRush: answers.handlesTaxRush || false,
      hasOtherIncome: answers.hasOtherIncome || false
    };

    this.calculateDashboardResults();
  }

  calculateDashboardResults(): void {
    const data = this.inputsData;
    
    debugLog('AppComponent', 'calculateDashboardResults_start', { 
      region: data.region,
      avgNetFee: data.avgNetFee,
      taxPrepReturns: data.taxPrepReturns,
      discountsPct: data.discountsPct,
      handlesTaxRush: data.handlesTaxRush,
      taxRushReturns: data.taxRushReturns
    });
    
    // Basic calculations
    const grossFees = data.avgNetFee * data.taxPrepReturns;
    const discounts = grossFees * (data.discountsPct / 100);
    const taxPrepIncome = grossFees - discounts;
    const taxRushIncome = data.region === 'CA' && data.handlesTaxRush ? data.taxRushReturns * 125 : 0;
    const otherIncome = data.hasOtherIncome ? data.otherIncome : 0;
    const totalRevenue = taxPrepIncome + taxRushIncome + otherIncome;
    
    debugLog('AppComponent', 'calculateDashboardResults_revenue', {
      grossFees,
      discounts,
      taxPrepIncome,
      taxRushIncome,
      otherIncome,
      totalRevenue
    });
    
    // Calculate expenses
    const salaries = grossFees * (data.salariesPct / 100);
    const empDeductions = salaries * (data.empDeductionsPct / 100);
    const rent = taxPrepIncome * (data.rentPct / 100);
    const supplies = taxPrepIncome * (data.suppliesPct / 100);
    const royalties = taxPrepIncome * (data.royaltiesPct / 100);
    const advRoyalties = taxPrepIncome * (data.advRoyaltiesPct / 100);
    const taxRushRoyalties = data.region === 'CA' && data.handlesTaxRush ? taxPrepIncome * (data.taxRushRoyaltiesPct / 100) : 0;
    const misc = taxPrepIncome * (data.miscPct / 100);
    
    const totalExpenses = salaries + empDeductions + rent + data.telephoneAmt + data.utilitiesAmt + 
                         data.localAdvAmt + data.insuranceAmt + data.postageAmt + supplies + 
                         data.duesAmt + data.bankFeesAmt + data.maintenanceAmt + data.travelEntAmt + 
                         royalties + advRoyalties + taxRushRoyalties + misc;
    
    const netIncome = totalRevenue - totalExpenses;
    const netMarginPct = totalRevenue > 0 ? (netIncome / totalRevenue) * 100 : 0;
    const costPerReturn = data.taxPrepReturns > 0 ? totalExpenses / data.taxPrepReturns : 0;
    const totalReturns = data.taxPrepReturns + (data.taxRushReturns || 0);
    
    debugLog('AppComponent', 'calculateDashboardResults_final', {
      totalExpenses,
      netIncome,
      netMarginPct,
      costPerReturn,
      totalReturns
    });

    // Update calculation results
    this.calculationResults = {
      netIncome,
      netMarginPct,
      costPerReturn,
      grossFees,
      discounts,
      taxPrepIncome,
      taxRushIncome,
      otherIncome,
      totalRevenue,
      totalExpenses,
      totalReturns,
      salaries,
      empDeductions,
      rent,
      telephone: data.telephoneAmt,
      utilities: data.utilitiesAmt,
      localAdv: data.localAdvAmt,
      insurance: data.insuranceAmt,
      postage: data.postageAmt,
      supplies,
      dues: data.duesAmt,
      bankFees: data.bankFeesAmt,
      maintenance: data.maintenanceAmt,
      travelEnt: data.travelEntAmt,
      royalties,
      advRoyalties,
      taxRushRoyalties,
      misc
    };

    // Update projected performance data
    this.projectedPerformanceData = {
      grossFees,
      discounts,
      taxPrepIncome,
      taxRushIncome,
      totalRevenue,
      totalExpenses,
      netIncome,
      netMarginPct,
      costPerReturn,
      totalReturns,
      region: data.region,
      lastYearRevenue: 0, // TODO: Load from persistence
      lastYearExpenses: 0, // TODO: Load from persistence
      lastYearReturns: 0, // TODO: Load from persistence
      expectedGrowthPct: 0, // TODO: Load from persistence
      handlesTaxRush: data.handlesTaxRush
    };
  }

  // Debug system event handlers
  onDebugSaveNow(): void {
    console.log('🐛 Debug: Save Now requested');
    this.persistence.saveBaseline(this.appStateService.currentState);
  }

  onDebugDumpStorage(): void {
    console.log('🐛 Debug: Dump Storage requested');
    this.persistence.dumpStorage();
  }

  onDebugCopyJSON(): void {
    console.log('🐛 Debug: Copy JSON requested');
    const data = {
      appState: this.appState,
      inputsData: this.inputsData,
      calculationResults: this.calculationResults,
      projectedPerformanceData: this.projectedPerformanceData
    };
    navigator.clipboard.writeText(JSON.stringify(data, null, 2)).then(() => {
      console.log('✅ Debug data copied to clipboard');
    });
  }

  onDebugClearStorage(): void {
    console.log('🐛 Debug: Clear Storage requested');
    this.persistence.clearStorage();
  }

  onDebugThresholdsChange(thresholds: any): void {
    console.log('🐛 Debug: Thresholds changed', thresholds);
    // TODO: Implement threshold change handling
  }
}
