// react-app-reference/react-app-reference/src/components/Wizard/ToggleQuestion.tsx
// ToggleQuestion.tsx - Reusable toggle question component for wizard sections
// Eliminates duplication between NewStoreSection and ExistingStoreSection

import React from 'react';
import type { WizardAnswers } from './types';

interface ToggleQuestionProps {
  title: string;
  description: string;
  fieldName: keyof WizardAnswers;
  fieldValue: boolean | undefined;
  positiveLabel: string;
  negativeLabel: string;
  onUpdate: (updates: Partial<WizardAnswers>) => void;
  fieldsToeClearOnDisable?: (keyof WizardAnswers)[];
  titleColor?: string;
  showOnlyWhen?: boolean; // Optional condition to show the toggle
}

export default function ToggleQuestion({
  title,
  description,
  fieldName,
  fieldValue,
  positiveLabel,
  negativeLabel,
  onUpdate,
  fieldsToeClearOnDisable = [],
  titleColor = '#6b7280',
  showOnlyWhen = true,
}: ToggleQuestionProps) {
  if (!showOnlyWhen) {
    return null;
  }

  return (
    <div
      style={{
        marginBottom: '1rem',
        padding: '0.75rem',
        backgroundColor: '#f8fafc',
        borderRadius: '6px',
        border: '1px solid #e2e8f0',
      }}
    >
      <div style={{ marginBottom: '0.5rem' }}>
        <label style={{ fontWeight: 600, color: titleColor }}>{title}</label>
      </div>
      <div style={{ marginBottom: '0.5rem', fontSize: '0.9rem', color: '#475569' }}>
        {description}
      </div>
      <div style={{ display: 'flex', gap: '1rem' }}>
        <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer' }}>
          <input
            type="radio"
            name={fieldName}
            checked={fieldValue === true}
            onChange={() => onUpdate({ [fieldName]: true })}
            style={{ marginRight: '0.25rem' }}
          />
          <span style={{ fontWeight: 500 }}>{positiveLabel}</span>
        </label>
        <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer' }}>
          <input
            type="radio"
            name={fieldName}
            checked={fieldValue === false}
            onChange={() => {
              // Clear related fields when disabling
              const clearUpdates = fieldsToeClearOnDisable.reduce((acc, field) => {
                acc[field] = undefined;
                return acc;
              }, {} as Partial<WizardAnswers>);

              onUpdate({
                [fieldName]: false,
                ...clearUpdates,
              });
            }}
            style={{ marginRight: '0.25rem' }}
          />
          <span style={{ fontWeight: 500 }}>{negativeLabel}</span>
        </label>
      </div>
    </div>
  );
}

// angular/src/app/components/wizard-ui/toggle-question.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'lt-toggle-question',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div 
      *ngIf="showOnlyWhen"
      class="toggle-section"
      style="margin-bottom: 1rem; padding: 0.75rem; background: #f8fafc; border-radius: 6px; border: 1px solid #e2e8f0;"
    >
      <div style="margin-bottom: 0.5rem;">
        <label style="font-weight: 600;" [style.color]="titleColor">{{ title }}</label>
      </div>
      <div style="margin-bottom: 0.5rem; font-size: 0.9rem; color: #475569;">
        {{ description }}
      </div>
      <div style="display: flex; gap: 1rem;">
        <label style="display: flex; align-items: center; gap: 0.5rem; cursor: pointer;">
          <input
            type="radio"
            [name]="fieldName"
            [checked]="fieldValue === true"
            (change)="onPositiveChange()"
            style="margin-right: 0.25rem;"
          />
          <span style="font-weight: 500;">{{ positiveLabel }}</span>
        </label>
        <label style="display: flex; align-items: center; gap: 0.5rem; cursor: pointer;">
          <input
            type="radio"
            [name]="fieldName"
            [checked]="fieldValue === false"
            (change)="onNegativeChange()"
            style="margin-right: 0.25rem;"
          />
          <span style="font-weight: 500;">{{ negativeLabel }}</span>
        </label>
      </div>
    </div>
  `,
})
export class ToggleQuestionComponent {
  @Input() title = '';
  @Input() description = '';
  @Input() fieldName = '';
  @Input() fieldValue?: boolean;
  @Input() positiveLabel = '';
  @Input() negativeLabel = '';
  @Input() fieldsToeClearOnDisable: string[] = [];
  @Input() titleColor = '#6b7280';
  @Input() showOnlyWhen = true;
  
  @Output() valueChange = new EventEmitter<{ [key: string]: any }>();

  onPositiveChange(): void {
    this.valueChange.emit({ [this.fieldName]: true });
  }

  onNegativeChange(): void {
    // Clear related fields when disabling
    const clearUpdates: { [key: string]: any } = {};
    this.fieldsToeClearOnDisable.forEach(field => {
      clearUpdates[field] = undefined;
    });

    this.valueChange.emit({
      [this.fieldName]: false,
      ...clearUpdates,
    });
  }
}
