// src/app/components/footer/footer.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule],
  template: `
    <footer class="footer-section">
      <div class="footer-grid">
        <div class="footer-column">
          <h4 class="footer-title">Navigation</h4>
          <ul class="footer-links">
            <li><a href="#" class="footer-link" [class.active]="currentPage === 'wizard'" (click)="onNavigate('wizard')">Setup Wizard</a></li>
            <li><a href="#" class="footer-link" [class.active]="currentPage === 'dashboard'" (click)="onNavigate('dashboard')">Dashboard</a></li>
            <li><a href="#" class="footer-link" (click)="onNavigate('reports')">Reports</a></li>
          </ul>
        </div>
        
        <div class="footer-column">
          <h4 class="footer-title">Quick Links</h4>
          <ul class="footer-links">
            <li><a href="#" class="footer-link" (click)="onNavigate('pro-tips')">Pro-Tips</a></li>
            <li><a href="#" class="footer-link" (click)="onNavigate('practice')">Practice Problems</a></li>
            <li><a href="#" class="footer-link" (click)="onNavigate('export')">Export (PDF/Excel)</a></li>
            <li><a href="#" class="footer-link" (click)="onNavigate('support')">Support Center</a></li>
          </ul>
        </div>
        
        <div class="footer-column">
          <h4 class="footer-title">Resources</h4>
          <ul class="footer-links">
            <li><a href="#" class="footer-link" (click)="onNavigate('settings')">Settings</a></li>
            <li><a href="#" class="footer-link" (click)="onNavigate('training')">Training Materials</a></li>
          </ul>
        </div>
        
        <div class="footer-column">
          <h4 class="footer-title">About & Status</h4>
          <div class="footer-content">
            <p class="footer-text">P&L Budget & Forecast</p>
            <p class="footer-text">Version 0.5 Preview</p>
            <p class="footer-text">Liberty Tax Service</p>
          </div>
        </div>
      </div>
      
      <div class="footer-copyright">
        © 2024 Liberty Tax Service. All rights reserved. P&L Budget & Forecast v0.5 Preview
      </div>
    </footer>
  `,
  styles: [`
    .footer-section {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 0.5rem;
      padding: 2rem;
      margin-top: 2rem;
    }

    .footer-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 2rem;
      margin-bottom: 2rem;
    }

    .footer-column {
      display: flex;
      flex-direction: column;
    }

    .footer-title {
      font-size: 1rem;
      font-weight: 600;
      color: #1f2937;
      margin: 0 0 1rem 0;
    }

    .footer-links {
      list-style: none;
      padding: 0;
      margin: 0;
    }

    .footer-links li {
      margin-bottom: 0.5rem;
    }

    .footer-link {
      color: #6b7280;
      text-decoration: none;
      font-size: 0.875rem;
      transition: color 0.15s ease-in-out;
      cursor: pointer;
    }

    .footer-link:hover {
      color: #374151;
    }

    .footer-link.active {
      color: #3b82f6;
      font-weight: 500;
    }

    .footer-content {
      display: flex;
      flex-direction: column;
      gap: 0.5rem;
    }

    .footer-text {
      font-size: 0.875rem;
      color: #6b7280;
      margin: 0;
    }

    .footer-copyright {
      text-align: center;
      font-size: 0.75rem;
      color: #9ca3af;
      padding-top: 1rem;
      border-top: 1px solid #e5e7eb;
    }

    @media (max-width: 768px) {
      .footer-grid {
        grid-template-columns: 1fr;
        gap: 1rem;
      }
    }
  `]
})
export class FooterComponent {
  @Input() showWizard: boolean = true;
  @Input() wizardCompleted: boolean = false;
  @Input() currentPage: string = 'wizard';

  @Output() onNavigate = new EventEmitter<string>();

  onNavigateClick(page: string): void {
    this.onNavigate.emit(page);
  }
}

<footer class="footer-section">
  <div class="footer-grid">
    <div class="footer-column">
      <h4 class="footer-title">Navigation</h4>
      <ul class="footer-links">
        <li><a href="#" class="footer-link" [class.active]="currentPage === 'wizard'" (click)="onNavigateClick('wizard')">Setup Wizard</a></li>
        <li><a href="#" class="footer-link" [class.active]="currentPage === 'dashboard'" (click)="onNavigateClick('dashboard')">Dashboard</a></li>
        <li><a href="#" class="footer-link" (click)="onNavigateClick('reports')">Reports</a></li>
      </ul>
    </div>
    
    <div class="footer-column">
      <h4 class="footer-title">Quick Links</h4>
      <ul class="footer-links">
        <li><a href="#" class="footer-link" (click)="onNavigateClick('pro-tips')">Pro-Tips</a></li>
        <li><a href="#" class="footer-link" (click)="onNavigateClick('practice')">Practice Problems</a></li>
        <li><a href="#" class="footer-link" (click)="onNavigateClick('export')">Export (PDF/Excel)</a></li>
        <li><a href="#" class="footer-link" (click)="onNavigateClick('support')">Support Center</a></li>
      </ul>
    </div>
    
    <div class="footer-column">
      <h4 class="footer-title">Resources</h4>
      <ul class="footer-links">
        <li><a href="#" class="footer-link" (click)="onNavigateClick('settings')">Settings</a></li>
        <li><a href="#" class="footer-link" (click)="onNavigateClick('training')">Training Materials</a></li>
      </ul>
    </div>
    
    <div class="footer-column">
      <h4 class="footer-title">About & Status</h4>
      <div class="footer-content">
        <p class="footer-text">P&L Budget & Forecast</p>
        <p class="footer-text">Version 0.5 Preview</p>
        <p class="footer-text">Liberty Tax Service</p>
      </div>
    </div>
  </div>
  
  <div class="footer-copyright">
    © 2024 Liberty Tax Service. All rights reserved. P&L Budget & Forecast v0.5 Preview
  </div>
</footer>

// react-app-reference/react-app-reference/src/components/Footer.tsx
// Footer.tsx - Professional navigation footer
// Multi-column layout with app navigation and external links

import React from 'react';

interface FooterProps {
  onNavigate?: (page: string) => void;
  showWizard?: boolean;
  wizardCompleted?: boolean;
  currentPage?: 'wizard' | 'dashboard' | 'reports';
}

export default function Footer({
  onNavigate,
  showWizard = false,
  wizardCompleted = false,
  currentPage = 'wizard',
}: FooterProps) {
  const handleNavClick = (page: string) => {
    if (onNavigate) {
      onNavigate(page);
    }
  };

  return (
    <footer
      style={{
        marginTop: 'auto',
        borderTop: '1px solid #e5e7eb',
        backgroundColor: '#f9fafb',
        padding: '2rem 1rem 1rem',
      }}
    >
      <div
        style={{
          maxWidth: '1200px',
          margin: '0 auto',
          display: 'grid',
          gridTemplateColumns: '1fr 1fr 1fr 1.5fr', // About column wider, others closer
          gap: '1.5rem',
          fontSize: '0.875rem',
        }}
      >
        {/* App Navigation Column */}
        <div>
          <h3
            style={{
              fontSize: '1rem',
              fontWeight: 600,
              color: '#1f2937',
              marginBottom: '1rem',
            }}
          >
            Navigation
          </h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
            <button
              onClick={() => handleNavClick('wizard')}
              style={{
                background: 'none',
                border: 'none',
                color: currentPage === 'wizard' ? '#2563eb' : '#6b7280',
                fontWeight: currentPage === 'wizard' ? 600 : 400,
                textAlign: 'left',
                cursor: 'pointer',
                padding: '0.25rem 0',
                fontSize: '0.875rem',
              }}
            >
              🚀 Setup Wizard
            </button>
            <button
              onClick={() => handleNavClick('dashboard')}
              disabled={!wizardCompleted}
              style={{
                background: 'none',
                border: 'none',
                color: wizardCompleted
                  ? currentPage === 'dashboard'
                    ? '#2563eb'
                    : '#6b7280'
                  : '#d1d5db',
                fontWeight: currentPage === 'dashboard' ? 600 : 400,
                textAlign: 'left',
                cursor: wizardCompleted ? 'pointer' : 'not-allowed',
                padding: '0.25rem 0',
                fontSize: '0.875rem',
              }}
            >
              📊 Dashboard
            </button>
            <button
              onClick={() => handleNavClick('reports')}
              disabled={!wizardCompleted}
              style={{
                background: 'none',
                border: 'none',
                color: wizardCompleted
                  ? currentPage === 'reports'
                    ? '#2563eb'
                    : '#6b7280'
                  : '#d1d5db',
                fontWeight: currentPage === 'reports' ? 600 : 400,
                textAlign: 'left',
                cursor: wizardCompleted ? 'pointer' : 'not-allowed',
                padding: '0.25rem 0',
                fontSize: '0.875rem',
              }}
            >
              📈 Reports
            </button>
          </div>
        </div>

        {/* Quick Links Column */}
        <div>
          <h3
            style={{
              fontSize: '1rem',
              fontWeight: 600,
              color: '#1f2937',
              marginBottom: '1rem',
            }}
          >
            Quick Links
          </h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
            <button
              onClick={() => handleNavClick('pro-tips')}
              style={{
                background: 'none',
                border: 'none',
                color: '#6b7280',
                textAlign: 'left',
                cursor: 'pointer',
                padding: '0.25rem 0',
                fontSize: '0.875rem',
              }}
            >
              💡 Pro-Tips <span style={{ color: '#d1d5db', fontSize: '0.75rem' }}>*</span>
            </button>
            <button
              onClick={() => handleNavClick('practice')}
              style={{
                background: 'none',
                border: 'none',
                color: '#6b7280',
                textAlign: 'left',
                cursor: 'pointer',
                padding: '0.25rem 0',
                fontSize: '0.875rem',
              }}
            >
              🎯 Practice Problems <span style={{ color: '#d1d5db', fontSize: '0.75rem' }}>*</span>
            </button>
            <button
              onClick={() => handleNavClick('export')}
              disabled={!wizardCompleted}
              style={{
                background: 'none',
                border: 'none',
                color: wizardCompleted ? '#6b7280' : '#d1d5db',
                textAlign: 'left',
                cursor: wizardCompleted ? 'pointer' : 'not-allowed',
                padding: '0.25rem 0',
                fontSize: '0.875rem',
              }}
            >
              📄 Export (PDF/Excel) <span style={{ color: '#d1d5db', fontSize: '0.75rem' }}>*</span>
            </button>
          </div>
        </div>

        {/* External Resources Column - Scaffolding */}
        <div>
          <h3
            style={{
              fontSize: '1rem',
              fontWeight: 600,
              color: '#1f2937',
              marginBottom: '1rem',
            }}
          >
            Resources
          </h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
            <button
              onClick={() => handleNavClick('settings')}
              style={{
                background: 'none',
                border: 'none',
                color: '#9ca3af',
                textAlign: 'left',
                cursor: 'not-allowed',
                padding: '0.25rem 0',
                fontSize: '0.875rem',
              }}
            >
              ⚙️ Settings <span style={{ color: '#d1d5db', fontSize: '0.75rem' }}>*</span>
            </button>
            <a
              href="#"
              onClick={(e) => e.preventDefault()}
              style={{
                color: '#9ca3af',
                textDecoration: 'none',
                padding: '0.25rem 0',
                fontSize: '0.875rem',
                cursor: 'not-allowed',
              }}
            >
              📚 Training Materials <span style={{ color: '#d1d5db', fontSize: '0.75rem' }}>*</span>
            </a>
            <a
              href="#"
              onClick={(e) => e.preventDefault()}
              style={{
                color: '#9ca3af',
                textDecoration: 'none',
                padding: '0.25rem 0',
                fontSize: '0.875rem',
                cursor: 'not-allowed',
              }}
            >
              📞 Support Center <span style={{ color: '#d1d5db', fontSize: '0.75rem' }}>*</span>
            </a>
          </div>
        </div>

        {/* About/Version Column - Wider */}
        <div>
          <h3
            style={{
              fontSize: '1rem',
              fontWeight: 600,
              color: '#1f2937',
              marginBottom: '1rem',
            }}
          >
            About & Status
          </h3>
          <div
            style={{
              fontSize: '0.75rem',
              color: '#6b7280',
              lineHeight: '1.5',
            }}
          >
            <div style={{ marginBottom: '0.5rem' }}>
              <strong style={{ color: '#374151' }}>P&L Budget & Forecast</strong>
            </div>
            <div style={{ marginBottom: '0.5rem' }}>Version 0.5 Preview</div>
            <div style={{ marginBottom: '1rem' }}>Liberty Tax Service</div>

            {/* Progress Milestones for Stakeholders */}
            <div
              style={{
                fontSize: '0.625rem',
                color: '#059669',
                marginBottom: '0.75rem',
                lineHeight: '1.4',
              }}
            >
              <div style={{ fontWeight: 500, color: '#374151', marginBottom: '0.25rem' }}>
                🚀 Current Milestones:
              </div>
              <div>✅ Wizard-driven setup complete</div>
              <div>✅ Modular component architecture</div>
              <div>✅ Regional branding & features</div>
              <div>✅ Real-time calculations & validation</div>
            </div>

            <div
              style={{
                fontSize: '0.625rem',
                color: '#9ca3af',
                borderTop: '1px solid #e5e7eb',
                paddingTop: '0.5rem',
              }}
            >
              Data persisted locally • Regional features active
              <br />
              <span style={{ color: '#d1d5db' }}>* Feature in development</span>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}
