// src/app/components/brand-watermark/brand-watermark.component.ts
import { Component, Input, OnInit, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Region } from '../../models/wizard.models';
import { BrandingService } from '../../services/branding.service';

@Component({
  selector: 'app-brand-watermark',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div 
      class="brand-watermark"
      [style.opacity]="0.05">
      <img
        [src]="watermarkUrl"
        [alt]="watermarkAlt"
        class="watermark-image"
        (error)="onImageError($event)"
      />
    </div>
  `,
  styles: [`
    .brand-watermark {
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      z-index: 0; /* Behind all content */
      pointer-events: none; /* Don't interfere with clicks */
      user-select: none; /* Can't be selected */
    }

    .watermark-image {
      width: 800px;
      height: auto;
      max-width: 70vw; /* More responsive sizing - fills more space */
      max-height: 70vh; /* Taller on desktop */
      min-width: 320px; /* Minimum size for mobile */
      object-fit: contain;
      filter: grayscale(20%); /* Slightly reduce saturation for watermark effect */
    }

    .watermark-image.hidden {
      display: none;
    }

    @media (max-width: 768px) {
      .watermark-image {
        width: 400px;
        min-width: 280px;
      }
    }
  `]
})
export class BrandWatermarkComponent implements OnInit, OnChanges {
  @Input() region: Region = 'US';

  watermarkUrl: string = '';
  watermarkAlt: string = '';

  constructor(private brandingService: BrandingService) {}

  ngOnInit(): void {
    this.updateWatermark();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['region']) {
      this.updateWatermark();
    }
  }

  private updateWatermark(): void {
    const assets = this.brandingService.getBrandAssets(this.region);
    this.watermarkUrl = assets.watermarkUrl;
    this.watermarkAlt = `${this.region === 'CA' ? 'Liberty Tax Canada' : 'Liberty Tax'} watermark`;
  }

  onImageError(event: any): void {
    console.warn(`Failed to load watermark for ${this.region} region`);
    event.target.classList.add('hidden');
  }
}

// src/components/BrandWatermark.tsx
// BrandWatermark.tsx - Regional brand watermark component
// Displays centered, scrolling watermark logo with proper transparency

import React from 'react'
import { useBrandAssets } from '../hooks/useBranding'
import type { Region } from '../lib/calcs'

interface BrandWatermarkProps {
  region: Region
}

export default function BrandWatermark({ region }: BrandWatermarkProps) {
  const assets = useBrandAssets(region)

  return (
    <div 
      className="brand-watermark"
      style={{
        position: 'fixed',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
        zIndex: 0, // Behind all content
        pointerEvents: 'none', // Don't interfere with clicks
        opacity: 0.05, // Very subtle transparency
        userSelect: 'none' // Can't be selected
      }}
    >
      <img
        src={assets.watermarkUrl}
        alt={`${region === 'US' ? 'Liberty Tax' : 'Liberty Tax Canada'} watermark`}
        style={{
          width: '800px',
          height: 'auto',
          maxWidth: '70vw', // More responsive sizing - fills more space
          maxHeight: '70vh', // Taller on desktop
          minWidth: '320px', // Minimum size for mobile
          objectFit: 'contain',
          filter: 'grayscale(20%)' // Slightly reduce saturation for watermark effect
        }}
        onError={(e) => {
          // Fallback if watermark image fails to load
          console.warn(`Failed to load watermark for ${region} region`)
          e.currentTarget.style.display = 'none'
        }}
      />
    </div>
  )
}

// Optional: Alternative text-based watermark if images aren't available
export function TextWatermark({ region }: BrandWatermarkProps) {
  const { brand } = useBranding(region)

  return (
    <div 
      className="brand-watermark-text"
      style={{
        position: 'fixed',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%) rotate(-45deg)',
        zIndex: 0,
        pointerEvents: 'none',
        opacity: 0.03,
        userSelect: 'none',
        fontSize: '8rem',
        fontWeight: 100,
        color: 'var(--brand-primary)',
        letterSpacing: '0.2em',
        whiteSpace: 'nowrap'
      }}
    >
      {brand.name.toUpperCase()}
    </div>
  )
}
