// react-app-reference/react-app-reference/src/app/components/inputs-panel/inputs-panel.component.ts
// inputs-panel.component.ts - Dashboard inputs with sliders and expense management
// Based on React app InputsPanel component

import { Component, Input, Output, EventEmitter, OnInit, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ExpenseField, getFieldsForRegion, getFieldsByCategory, InputsPanelData } from '../../models/expense.models';
import { formatCurrency, formatNumber } from '../../utils/calculation.utils';
import { debugLog, CalculationValidator } from '../../utils/debug.utils';

@Component({
  selector: 'app-inputs-panel',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="card inputs-panel-card">
      <div class="card-title">Inputs</div>

      <!-- Scenario Selector -->
      <div class="scenario-section">
        <label>
          <strong>Scenario:</strong>&nbsp;
          <select
            [(ngModel)]="data.scenario"
            (ngModelChange)="onScenarioChange($event)"
            class="scenario-select">
            <option value="Custom">Custom</option>
            <option value="Good">Good</option>
            <option value="Better">Better</option>
            <option value="Best">Best</option>
          </select>
        </label>
      </div>

      <!-- Income Drivers Section -->
      <div class="income-drivers-section">
        <div class="section-header">
          💰 Income Drivers
        </div>

        <!-- Average Net Fee with Slider -->
        <div class="input-with-slider">
          <div class="input-row">
            <label class="input-label">Average Net Fee</label>
            <div class="input-controls">
              <span class="currency-symbol">$</span>
              <input
                type="number"
                [(ngModel)]="data.avgNetFee"
                (ngModelChange)="onAvgNetFeeChange($event)"
                min="50"
                max="500"
                step="1"
                class="number-input">
            </div>
          </div>
          <input
            type="range"
            [(ngModel)]="data.avgNetFee"
            (ngModelChange)="onAvgNetFeeChange($event)"
            min="50"
            max="500"
            step="1"
            class="slider">
        </div>

        <!-- Tax-Prep Returns with Slider -->
        <div class="input-with-slider">
          <div class="input-row">
            <label class="input-label">Tax-Prep Returns</label>
            <div class="input-controls">
              <span class="number-symbol">#</span>
              <input
                type="number"
                [(ngModel)]="data.taxPrepReturns"
                (ngModelChange)="onTaxPrepReturnsChange($event)"
                min="100"
                max="10000"
                step="1"
                class="number-input">
            </div>
          </div>
          <input
            type="range"
            [(ngModel)]="data.taxPrepReturns"
            (ngModelChange)="onTaxPrepReturnsChange($event)"
            min="100"
            max="5000"
            step="1"
            class="slider">
        </div>

        <!-- TaxRush Returns (Canada only) with Slider -->
        <div *ngIf="data.region === 'CA'" class="taxrush-input-section">
          <div class="input-with-slider">
            <div class="input-row">
              <label class="input-label">TaxRush Returns</label>
              <div class="input-controls">
                <span class="number-symbol">#</span>
                <input
                  type="number"
                  [(ngModel)]="data.taxRushReturns"
                  (ngModelChange)="onTaxRushReturnsChange($event)"
                  min="0"
                  max="1000"
                  step="1"
                  class="number-input taxrush-input">
              </div>
            </div>
            <input
              type="range"
              [(ngModel)]="data.taxRushReturns"
              (ngModelChange)="onTaxRushReturnsChange($event)"
              min="0"
              max="1000"
              step="1"
              class="slider">
          </div>
        </div>

        <!-- Customer Discounts with Dual Input and Slider -->
        <div class="input-with-slider">
          <div class="input-row">
            <label class="input-label">Customer Discounts</label>
            <div class="dual-input-controls">
              <div class="input-group">
                <input
                  type="number"
                  [(ngModel)]="data.discountsPct"
                  (ngModelChange)="onDiscountsPctChange($event)"
                  min="0"
                  max="50"
                  step="0.1"
                  class="number-input">
                <span class="percentage-symbol">%</span>
              </div>
              <span class="equals-symbol">=</span>
              <div class="input-group">
                <span class="currency-symbol">$</span>
                <input
                  type="number"
                  [value]="discountDollarAmount"
                  (ngModelChange)="onDiscountDollarChange(+$event)"
                  min="0"
                  step="1"
                  class="number-input dollar-input">
              </div>
            </div>
          </div>
          <input
            type="range"
            [(ngModel)]="data.discountsPct"
            (ngModelChange)="onDiscountsPctChange($event)"
            min="0"
            max="25"
            step="1"
            class="slider">
        </div>

        <!-- Other Income (conditional) -->
        <div *ngIf="data.hasOtherIncome" class="input-with-slider">
          <div class="input-row">
            <label class="input-label">Other Income</label>
            <div class="input-controls">
              <button
                type="button"
                title="Additional revenue sources (e.g., notary services, business consulting)"
                class="help-button">
                ℹ️
              </button>
              <span class="currency-symbol">$</span>
              <input
                type="number"
                [(ngModel)]="data.otherIncome"
                (ngModelChange)="onOtherIncomeChange($event)"
                min="0"
                max="50000"
                step="100"
                class="number-input">
            </div>
          </div>
        </div>
      </div>

      <!-- Expense Management Section -->
      <div class="expense-management-section">
        <div class="section-header">
          📊 Expense Management
        </div>
        
        <div class="expense-fields">
          <div *ngFor="let field of expenseFields" class="expense-field" [ngClass]="getFieldStyle(field)">
            <div class="field-header">
              <label class="field-label" [class.locked]="isFieldLocked(field)">
                {{ field.label }}
                <span *ngIf="isFieldLocked(field)" class="locked-text">(Locked)</span>
              </label>
              
              <div class="field-controls">
                <button
                  *ngIf="field.description"
                  type="button"
                  [title]="field.description"
                  class="help-button">
                  ℹ️
                </button>
                
                <!-- Percentage/Fixed Amount Input -->
                <div class="input-group">
                  <span *ngIf="isFixedAmount(field)" class="currency-symbol">$</span>
                  <input
                    type="number"
                    [value]="getFieldValue(field)"
                    (ngModelChange)="onFieldValueChange(field, +$event)"
                    [min]="field.min"
                    [max]="isFixedAmount(field) ? undefined : 100"
                    [step]="field.step"
                    [disabled]="isFieldDisabled(field) || isFieldLocked(field)"
                    class="field-input"
                    [class.taxrush-field]="isTaxRushField(field)">
                  <span *ngIf="!isFixedAmount(field)" class="percentage-symbol">%</span>
                </div>

                <!-- Dollar Input for percentage-based fields -->
                <div *ngIf="!isFixedAmount(field) && !isFieldLocked(field)" class="dollar-input-group">
                  <span class="equals-symbol">=</span>
                  <div class="input-group">
                    <span class="currency-symbol">$</span>
                    <input
                      type="number"
                      [value]="getDollarValue(field)"
                      (ngModelChange)="onDollarValueChange(field, +$event)"
                      min="0"
                      step="1"
                      [disabled]="isFieldDisabled(field) || grossFees === 0"
                      class="field-input dollar-input">
                  </div>
                </div>
              </div>
            </div>
            
            <!-- Slider for percentage-based fields -->
            <input
              *ngIf="!isFixedAmount(field) && !isFieldLocked(field)"
              type="range"
              [value]="getFieldValue(field)"
              (ngModelChange)="onFieldValueChange(field, +$event)"
              [min]="field.min"
              [max]="Math.min(field.max, 50)"
              [step]="field.step"
              [disabled]="isFieldDisabled(field)"
              class="field-slider">
            
            <div *ngIf="field.description" class="field-description">
              {{ field.description }}
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .inputs-panel-card {
      min-width: 420px;
      max-width: 500px;
    }

    .scenario-section {
      margin-bottom: 1.5rem;
    }

    .scenario-select {
      padding: 0.25rem;
      border-radius: 4px;
      border: 1px solid #d1d5db;
      font-size: 0.875rem;
    }

    .income-drivers-section,
    .expense-management-section {
      margin-bottom: 1.5rem;
      border: 1px solid #d1d5db;
      border-radius: 8px;
      padding: 1rem;
      background-color: #fafafa;
    }

    .section-header {
      display: flex;
      align-items: center;
      margin-bottom: 1rem;
      font-weight: 600;
      font-size: 1.1rem;
      border-bottom: 2px solid;
      padding-bottom: 0.25rem;
    }

    .income-drivers-section .section-header {
      color: #059669;
      border-bottom-color: #059669;
    }

    .expense-management-section .section-header {
      color: #6b7280;
      border-bottom-color: #6b7280;
    }

    .input-with-slider {
      margin-bottom: 0.75rem;
    }

    .input-row {
      display: grid;
      grid-template-columns: 1fr auto;
      gap: 0.5rem;
      align-items: center;
      margin-bottom: 0.5rem;
    }

    .input-label {
      font-size: 0.9rem;
      font-weight: 500;
    }

    .input-controls {
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }

    .dual-input-controls {
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }

    .input-group {
      display: flex;
      align-items: center;
      gap: 0.25rem;
    }

    .dollar-input-group {
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }

    .currency-symbol,
    .number-symbol,
    .percentage-symbol {
      font-size: 0.8rem;
      color: #6b7280;
    }

    .equals-symbol {
      color: #6b7280;
      font-size: 0.8rem;
    }

    .number-input,
    .field-input {
      width: 80px;
      padding: 0.25rem;
      border: 1px solid #d1d5db;
      border-radius: 4px;
      font-size: 0.8rem;
      text-align: right;
    }

    .dollar-input {
      width: 80px;
      background-color: #f9fafb;
    }

    .taxrush-input {
      background-color: #f0f9ff;
    }

    .slider,
    .field-slider {
      width: 100%;
      margin-bottom: 0.5rem;
    }

    .taxrush-input-section {
      border: 2px solid #3b82f6;
      border-radius: 8px;
      padding: 0.75rem;
      background-color: #f8fafc;
      margin-bottom: 0.75rem;
    }

    .help-button {
      background: none;
      border: none;
      color: #6b7280;
      cursor: help;
      font-size: 0.8rem;
      padding: 0;
      line-height: 1;
    }

    .expense-fields {
      display: flex;
      flex-direction: column;
      gap: 0.75rem;
    }

    .expense-field {
      margin-bottom: 0.75rem;
    }

    .expense-field.taxrush-field {
      border: 2px solid #3b82f6;
      border-radius: 6px;
      padding: 0.75rem;
      background-color: #f8fafc;
    }

    .field-header {
      display: grid;
      grid-template-columns: 1fr auto;
      gap: 0.5rem;
      align-items: center;
      margin-bottom: 0.5rem;
    }

    .field-label {
      font-size: 0.9rem;
      font-weight: 500;
    }

    .field-label.locked {
      color: #6b7280;
    }

    .locked-text {
      font-size: 0.8rem;
      color: #6b7280;
    }

    .field-controls {
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }

    .field-description {
      font-size: 0.75rem;
      color: #6b7280;
      margin-top: 0.25rem;
    }
  `]
})
export class InputsPanelComponent implements OnInit, OnChanges {
  @Input() data!: InputsPanelData;
  @Output() dataChange = new EventEmitter<InputsPanelData>();

  expenseFields: ExpenseField[] = [];
  grossFees: number = 0;
  discountDollarAmount: number = 0;

  // Utility methods
  formatCurrency = formatCurrency;
  formatNumber = formatNumber;
  Math = Math;

  ngOnInit(): void {
    this.updateExpenseFields();
    this.calculateDerivedValues();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['data']) {
      this.updateExpenseFields();
      this.calculateDerivedValues();
    }
  }

  updateExpenseFields(): void {
    this.expenseFields = getFieldsForRegion(this.data.region).filter(field => {
      // Filter out TaxRush-related fields if handlesTaxRush is false
      const isTaxRushField = field.id === 'taxRushRoyaltiesPct' || field.id === 'taxRushShortagesPct';
      if (isTaxRushField && this.data.handlesTaxRush === false) return false;
      return true;
    });
  }

  calculateDerivedValues(): void {
    this.grossFees = this.data.avgNetFee * this.data.taxPrepReturns;
    this.discountDollarAmount = this.grossFees * (this.data.discountsPct / 100);
  }

  // Event handlers
  onScenarioChange(scenario: string): void {
    this.data.scenario = scenario as any;
    this.emitChange();
  }

  onAvgNetFeeChange(value: number): void {
    debugLog('InputsPanel', 'onAvgNetFeeChange', { oldValue: this.data.avgNetFee, newValue: value });
    this.data.avgNetFee = Math.max(50, Math.min(500, value || 50));
    this.calculateDerivedValues();
    this.emitChange();
  }

  onTaxPrepReturnsChange(value: number): void {
    this.data.taxPrepReturns = Math.max(100, Math.min(10000, value || 100));
    this.calculateDerivedValues();
    this.emitChange();
  }

  onTaxRushReturnsChange(value: number): void {
    this.data.taxRushReturns = Math.max(0, Math.min(1000, value || 0));
    this.emitChange();
  }

  onDiscountsPctChange(value: number): void {
    this.data.discountsPct = Math.max(0, Math.min(50, value || 0));
    this.calculateDerivedValues();
    this.emitChange();
  }

  onDiscountDollarChange(value: number): void {
    const validDollar = Math.max(0, value || 0);
    if (this.grossFees > 0) {
      const newPct = (validDollar / this.grossFees) * 100;
      this.data.discountsPct = Math.max(0, Math.min(50, newPct));
      this.calculateDerivedValues();
      this.emitChange();
    }
  }

  onOtherIncomeChange(value: number): void {
    this.data.otherIncome = Math.max(0, Math.min(50000, value || 0));
    this.emitChange();
  }

  onFieldValueChange(field: ExpenseField, value: number): void {
    const validValue = Math.max(field.min, Math.min(field.max, value || field.min));
    this.setFieldValue(field, validValue);
    this.emitChange();
  }

  onDollarValueChange(field: ExpenseField, value: number): void {
    const validDollar = Math.max(0, value || 0);
    if (this.isFixedAmount(field)) {
      this.setFieldValue(field, validDollar);
    } else {
      let base = 0;
      if (field.calculationBase === 'percentage_gross') {
        base = this.grossFees;
      } else if (field.calculationBase === 'percentage_tp_income') {
        base = this.grossFees - this.discountDollarAmount;
      } else if (field.calculationBase === 'percentage_salaries') {
        base = this.grossFees * this.data.salariesPct / 100;
      }
      
      if (base > 0) {
        const newPercentage = Math.round(validDollar / base * 100);
        const cappedPercentage = Math.max(field.min, Math.min(field.max, newPercentage));
        this.setFieldValue(field, cappedPercentage);
      }
    }
    this.emitChange();
  }

  // Field utility methods
  getFieldValue(field: ExpenseField): number {
    return (this.data as any)[field.id] ?? field.defaultValue;
  }

  setFieldValue(field: ExpenseField, value: number): void {
    (this.data as any)[field.id] = value;
  }

  getDollarValue(field: ExpenseField): number {
    if (this.isFixedAmount(field)) {
      return this.getFieldValue(field);
    }

    const value = this.getFieldValue(field);
    if (field.calculationBase === 'percentage_gross') {
      return Math.round(this.grossFees * value / 100);
    } else if (field.calculationBase === 'percentage_tp_income') {
      const taxPrepIncome = this.grossFees - this.discountDollarAmount;
      return Math.round(taxPrepIncome * value / 100);
    } else if (field.calculationBase === 'percentage_salaries') {
      const salariesAmount = this.grossFees * this.data.salariesPct / 100;
      return Math.round(salariesAmount * value / 100);
    }
    return 0;
  }

  isFixedAmount(field: ExpenseField): boolean {
    return field.calculationBase === 'fixed_amount';
  }

  isFieldDisabled(field: ExpenseField): boolean {
    return field.regionSpecific === 'CA' && this.data.region !== 'CA';
  }

  isFieldLocked(field: ExpenseField): boolean {
    const isFranchiseRoyalty = field.category === 'franchise' && field.id.includes('oyalties');
    return isFranchiseRoyalty;
  }

  isTaxRushField(field: ExpenseField): boolean {
    return field.id === 'taxRushRoyaltiesPct';
  }

  getFieldStyle(field: ExpenseField): string {
    return this.isTaxRushField(field) ? 'taxrush-field' : '';
  }

  private emitChange(): void {
    this.dataChange.emit(this.data);
  }
}

// src/components/InputsPanel.tsx
// InputsPanel.tsx - Dashboard inputs mirroring wizard Page 2 structure
// Enhanced with sliders and bidirectional wizard data flow

import React, { useEffect } from 'react'
import type { Region } from '../lib/calcs'
import type { Scenario } from '../data/presets'
import type { WizardAnswers } from './Wizard/types'
import { 
  expenseFields, 
  expenseCategories,
  getFieldsByCategory,
  getFieldsForRegion,
  type ExpenseField,
  type ExpenseCategory 
} from '../types/expenses'

interface InputsPanelProps {
  // Basic fields
  region: Region
  scenario: Scenario
  setScenario: (scenario: Scenario) => void
  avgNetFee: number
  setANF: (value: number) => void
  taxPrepReturns: number
  setReturns: (value: number) => void
  taxRushReturns: number
  setTaxRush: (value: number) => void
  discountsPct: number
  setDisc: (value: number) => void

  // All 17 expense fields
  salariesPct: number
  setSal: (value: number) => void
  empDeductionsPct: number
  setEmpDeductions: (value: number) => void
  rentPct: number
  setRent: (value: number) => void
  telephoneAmt: number
  setTelephone: (value: number) => void
  utilitiesAmt: number
  setUtilities: (value: number) => void
  localAdvAmt: number
  setLocalAdv: (value: number) => void
  insuranceAmt: number
  setInsurance: (value: number) => void
  postageAmt: number
  setPostage: (value: number) => void
  suppliesPct: number
  setSup: (value: number) => void
  duesAmt: number
  setDues: (value: number) => void
  bankFeesAmt: number
  setBankFees: (value: number) => void
  maintenanceAmt: number
  setMaintenance: (value: number) => void
  travelEntAmt: number
  setTravelEnt: (value: number) => void
  royaltiesPct: number
  setRoy: (value: number) => void
  advRoyaltiesPct: number
  setAdvRoy: (value: number) => void
  taxRushRoyaltiesPct: number
  setTaxRushRoy: (value: number) => void
  miscPct: number
  setMisc: (value: number) => void

  // Bidirectional persistence functions
  onSaveToWizard?: (updates: Partial<WizardAnswers>) => void
  
  // TaxRush handling for expense field filtering
  handlesTaxRush?: boolean
}

export default function InputsPanel(props: InputsPanelProps) {
  const {
    region, scenario, setScenario, avgNetFee, setANF, taxPrepReturns, setReturns,
    taxRushReturns, setTaxRush, discountsPct, setDisc,
    salariesPct, setSal, empDeductionsPct, setEmpDeductions, rentPct, setRent,
    telephoneAmt, setTelephone, utilitiesAmt, setUtilities, localAdvAmt, setLocalAdv,
    insuranceAmt, setInsurance, postageAmt, setPostage, suppliesPct, setSup,
    duesAmt, setDues, bankFeesAmt, setBankFees, maintenanceAmt, setMaintenance,
    travelEntAmt, setTravelEnt, royaltiesPct, setRoy, advRoyaltiesPct, setAdvRoy,
    taxRushRoyaltiesPct, setTaxRushRoy, miscPct, setMisc, onSaveToWizard,
    handlesTaxRush = false
  } = props

  // 🔄 BIDIRECTIONAL FLOW: Save dashboard changes back to wizard persistence
  useEffect(() => {
    if (onSaveToWizard) {
      const wizardUpdates: Partial<WizardAnswers> = {
        avgNetFee,
        taxPrepReturns,
        taxRushReturns,
        discountsPct,
        // Expense fields
        salariesPct,
        empDeductionsPct,
        rentPct,
        telephoneAmt,
        utilitiesAmt,
        localAdvAmt,
        insuranceAmt,
        postageAmt,
        suppliesPct,
        duesAmt,
        bankFeesAmt,
        maintenanceAmt,
        travelEntAmt,
        royaltiesPct,
        advRoyaltiesPct,
        taxRushRoyaltiesPct,
        miscPct
      }
      
      console.log('🔄 Dashboard → Wizard: Saving changes to wizard persistence', wizardUpdates)
      onSaveToWizard(wizardUpdates)
    }
  }, [
    avgNetFee, taxPrepReturns, taxRushReturns, discountsPct,
    salariesPct, empDeductionsPct, rentPct, telephoneAmt, utilitiesAmt,
    localAdvAmt, insuranceAmt, postageAmt, suppliesPct, duesAmt,
    bankFeesAmt, maintenanceAmt, travelEntAmt, royaltiesPct,
    advRoyaltiesPct, taxRushRoyaltiesPct, miscPct, onSaveToWizard
  ])

  // Expense field value getters and setters mapping
  const getFieldValue = (field: ExpenseField) => {
    const fieldMap: any = {
      salariesPct, empDeductionsPct, rentPct, telephoneAmt, utilitiesAmt,
      localAdvAmt, insuranceAmt, postageAmt, suppliesPct, duesAmt,
      bankFeesAmt, maintenanceAmt, travelEntAmt, royaltiesPct,
      advRoyaltiesPct, taxRushRoyaltiesPct, miscPct
    }
    return fieldMap[field.id] ?? field.defaultValue
  }

  const setFieldValue = (field: ExpenseField, value: number) => {
    const setterMap: any = {
      salariesPct: setSal, empDeductionsPct: setEmpDeductions, rentPct: setRent,
      telephoneAmt: setTelephone, utilitiesAmt: setUtilities, localAdvAmt: setLocalAdv,
      insuranceAmt: setInsurance, postageAmt: setPostage, suppliesPct: setSup,
      duesAmt: setDues, bankFeesAmt: setBankFees, maintenanceAmt: setMaintenance,
      travelEntAmt: setTravelEnt, royaltiesPct: setRoy, advRoyaltiesPct: setAdvRoy,
      taxRushRoyaltiesPct: setTaxRushRoy, miscPct: setMisc
    }
    setterMap[field.id]?.(value)
  }

  // Get category icon (matching wizard)
  const getCategoryIcon = (category: ExpenseCategory): string => {
    switch (category) {
      case 'personnel': return '👥'
      case 'facility': return '🏢'
      case 'operations': return '⚙️'
      case 'franchise': return '🏪'
      case 'misc': return '📝'
      default: return '📊'
    }
  }

  // Calculate gross fees for discount calculation
  const grossFees = avgNetFee * taxPrepReturns
  const discountDollarAmount = grossFees * (discountsPct / 100)

  // Handle discount percentage/dollar changes
  const handleDiscountPctChange = (newPct: number) => {
    setDisc(Math.max(0, Math.min(50, newPct)))
  }

  const handleDiscountDollarChange = (newDollar: number) => {
    const validDollar = Math.max(0, newDollar)
    if (grossFees > 0) {
      const newPct = (validDollar / grossFees) * 100
      setDisc(Math.max(0, Math.min(50, newPct)))
    }
  }

  // Render expense field with dual percentage/dollar inputs and slider (enhanced for dashboard)
  const renderExpenseFieldWithSlider = (field: ExpenseField) => {
    const value = getFieldValue(field)
    const isFixed = field.calculationBase === 'fixed_amount'
    const isDisabled = field.regionSpecific === 'CA' && region !== 'CA'
    const isTaxRushField = field.id === 'taxRushRoyaltiesPct'
    const isFranchiseRoyalty = field.category === 'franchise' && field.id.includes('oyalties')
    const isLocked = isFranchiseRoyalty // Franchise royalties are locked
    
    // Calculate dollar value for percentage-based fields
    let dollarValue = 0
    if (!isFixed) {
      if (field.calculationBase === 'percentage_gross') {
        dollarValue = Math.round(grossFees * value / 100)
      } else if (field.calculationBase === 'percentage_tp_income') {
        const taxPrepIncome = grossFees - discountDollarAmount
        dollarValue = Math.round(taxPrepIncome * value / 100)
      } else if (field.calculationBase === 'percentage_salaries') {
        const salariesAmount = grossFees * salariesPct / 100
        dollarValue = Math.round(salariesAmount * value / 100)
      }
    }

    const handlePercentageChange = (newPercentage: number) => {
      const validPercentage = Math.max(0, Math.min(100, newPercentage))
      setFieldValue(field, validPercentage)
    }

    const handleDollarChange = (newDollar: number) => {
      const validDollar = Math.max(0, newDollar)
      if (isFixed) {
        setFieldValue(field, validDollar)
      } else {
        let base = 0
        if (field.calculationBase === 'percentage_gross') {
          base = grossFees
        } else if (field.calculationBase === 'percentage_tp_income') {
          base = grossFees - discountDollarAmount
        } else if (field.calculationBase === 'percentage_salaries') {
          base = grossFees * salariesPct / 100
        }
        
        if (base > 0) {
          const newPercentage = Math.round(validDollar / base * 100)
          const cappedPercentage = Math.max(0, Math.min(100, newPercentage))
          setFieldValue(field, cappedPercentage)
        }
      }
    }
    
    // Style for TaxRush fields (blue boxed)
    const fieldStyle = isTaxRushField ? {
      border: '2px solid #3b82f6',
      borderRadius: '6px',
      padding: '0.75rem',
      backgroundColor: '#f8fafc',
      marginBottom: '0.75rem'
    } : { marginBottom: '0.75rem' }

    return (
      <div key={field.id} style={fieldStyle}>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr auto', gap: '0.5rem', alignItems: 'center', marginBottom: '0.5rem' }}>
          <label style={{ fontSize: '0.9rem', fontWeight: 500, color: isLocked ? '#6b7280' : 'inherit' }}>
            {field.label}
            {isLocked && ' (Locked)'}
          </label>
          
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            {/* Percentage/Fixed Amount Input */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
              {isFixed && <span style={{ fontSize: '0.8rem', color: '#6b7280' }}>$</span>}
              <input
                type="number"
                min="0"
                max={isFixed ? undefined : 100}
                step="1"
                value={value}
                onChange={(e) => handlePercentageChange(Number(e.target.value) || 0)}
                disabled={isDisabled || isLocked}
                style={{
                  width: '60px',
                  padding: '0.25rem',
                  border: '1px solid #d1d5db',
                  borderRadius: '4px',
                  fontSize: '0.8rem',
                  textAlign: 'right',
                  backgroundColor: isDisabled ? '#f3f4f6' : isTaxRushField ? '#f0f9ff' : 'white'
                }}
              />
              {!isFixed && <span style={{ fontSize: '0.8rem', color: '#6b7280' }}>%</span>}
            </div>

            {/* Dollar Input - only for percentage-based fields */}
            {!isFixed && !isLocked && (
              <>
                <span style={{ color: '#6b7280', fontSize: '0.8rem' }}>=</span>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                  <span style={{ fontSize: '0.8rem', color: '#6b7280' }}>$</span>
                  <input
                    type="number"
                    min="0"
                    step="1"
                    value={dollarValue || ''}
                    onChange={(e) => handleDollarChange(Number(e.target.value) || 0)}
                    disabled={isDisabled || grossFees === 0}
                    placeholder="0"
                    style={{
                      width: '80px',
                      padding: '0.25rem',
                      border: '1px solid #d1d5db',
                      borderRadius: '4px',
                      fontSize: '0.8rem',
                      textAlign: 'right',
                      backgroundColor: '#f9fafb'
                    }}
                  />
                </div>
              </>
            )}
          </div>
        </div>
        
        {/* Slider for percentage-based fields */}
        {!isFixed && !isLocked && (
          <>
            <input
              type="range"
              min="0"
              max={Math.min(field.max, 50)} // Cap at reasonable max
              step={field.step}
              value={value}
              onChange={(e) => handlePercentageChange(Number(e.target.value))}
              disabled={isDisabled}
              style={{ width: '100%', marginBottom: '0.25rem' }}
            />
            <div style={{ fontSize: '0.75rem', color: '#6b7280', textAlign: 'center' }}>
              Range: 0% - {Math.min(field.max, 50)}%
            </div>
          </>
        )}
        
        {field.description && (
          <div style={{ fontSize: '0.75rem', color: '#6b7280', marginTop: '0.25rem' }}>
            {field.description}
          </div>
        )}
      </div>
    )
  }

  // Render expense field with dual percentage/dollar inputs (matching wizard Page 2)
  const renderExpenseField = (field: ExpenseField) => {
    const value = getFieldValue(field)
    const isFixed = field.calculationBase === 'fixed_amount'
    const isDisabled = field.regionSpecific === 'CA' && region !== 'CA'
    const isTaxRushField = field.id === 'taxRushRoyaltiesPct'
    const isFranchiseRoyalty = field.category === 'franchise' && field.id.includes('oyalties')
    const isLocked = isFranchiseRoyalty // Franchise royalties are locked
    
    // Calculate dollar value for percentage-based fields
    let dollarValue = 0
    if (!isFixed) {
      if (field.calculationBase === 'percentage_gross') {
        dollarValue = Math.round(grossFees * value / 100)
      } else if (field.calculationBase === 'percentage_tp_income') {
        const taxPrepIncome = grossFees - discountDollarAmount
        dollarValue = Math.round(taxPrepIncome * value / 100)
      } else if (field.calculationBase === 'percentage_salaries') {
        const salariesAmount = grossFees * salariesPct / 100
        dollarValue = Math.round(salariesAmount * value / 100)
      }
    }

    const handlePercentageChange = (newPercentage: number) => {
      const validPercentage = Math.max(0, Math.min(100, newPercentage))
      setFieldValue(field, validPercentage)
    }

    const handleDollarChange = (newDollar: number) => {
      const validDollar = Math.max(0, newDollar)
      if (isFixed) {
        setFieldValue(field, validDollar)
      } else {
        let base = 0
        if (field.calculationBase === 'percentage_gross') {
          base = grossFees
        } else if (field.calculationBase === 'percentage_tp_income') {
          base = grossFees - discountDollarAmount
        } else if (field.calculationBase === 'percentage_salaries') {
          base = grossFees * salariesPct / 100
        }
        
        if (base > 0) {
          const newPercentage = Math.round(validDollar / base * 100)
          const cappedPercentage = Math.max(0, Math.min(100, newPercentage))
          setFieldValue(field, cappedPercentage)
        }
      }
    }
    
    // Style for TaxRush fields (blue boxed)
    const fieldStyle = isTaxRushField ? {
      border: '2px solid #3b82f6',
      borderRadius: '6px',
      padding: '0.75rem',
      backgroundColor: '#f8fafc',
      marginBottom: '0.75rem'
    } : { marginBottom: '0.75rem' }

    return (
      <div key={field.id} style={fieldStyle}>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr auto', gap: '0.5rem', alignItems: 'center' }}>
          <label style={{ fontSize: '0.9rem', fontWeight: 500, color: isLocked ? '#6b7280' : 'inherit' }}>
            {field.label}
            {isLocked && ' (Locked)'}
          </label>
          
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            {/* Percentage/Fixed Amount Input */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
              {isFixed && <span style={{ fontSize: '0.8rem', color: '#6b7280' }}>$</span>}
              <input
                type="number"
                min="0"
                max={isFixed ? undefined : 100}
                step="1"
                value={value}
                onChange={(e) => handlePercentageChange(Number(e.target.value) || 0)}
                disabled={isDisabled || isLocked}
                style={{
                  width: '60px',
                  padding: '0.25rem',
                  border: '1px solid #d1d5db',
                  borderRadius: '4px',
                  fontSize: '0.8rem',
                  textAlign: 'right',
                  backgroundColor: isDisabled ? '#f3f4f6' : isTaxRushField ? '#f0f9ff' : 'white'
                }}
              />
              {!isFixed && <span style={{ fontSize: '0.8rem', color: '#6b7280' }}>%</span>}
            </div>

            {/* Dollar Input - only for percentage-based fields */}
            {!isFixed && !isLocked && (
              <>
                <span style={{ color: '#6b7280', fontSize: '0.8rem' }}>=</span>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                  <span style={{ fontSize: '0.8rem', color: '#6b7280' }}>$</span>
                  <input
                    type="number"
                    min="0"
                    step="1"
                    value={dollarValue || ''}
                    onChange={(e) => handleDollarChange(Number(e.target.value) || 0)}
                    disabled={isDisabled || grossFees === 0}
                    placeholder="0"
                    style={{
                      width: '80px',
                      padding: '0.25rem',
                      border: '1px solid #d1d5db',
                      borderRadius: '4px',
                      fontSize: '0.8rem',
                      textAlign: 'right',
                      backgroundColor: '#f9fafb'
                    }}
                  />
                </div>
              </>
            )}
          </div>
        </div>
        
        {field.description && (
          <div style={{ fontSize: '0.75rem', color: '#6b7280', marginTop: '0.25rem' }}>
            {field.description}
          </div>
        )}
      </div>
    )
  }

  return (
    <div className="card" style={{ minWidth: '420px', maxWidth: '500px' }}>
      <div className="card-title">Inputs</div>

      {/* Scenario Selector - IMPORTANT for post-wizard adjustments */}
      <div style={{ marginBottom: '1.5rem' }}>
        <label>
          <strong>Scenario:</strong>&nbsp;
          <select
            value={scenario}
            onChange={(e) => setScenario(e.target.value as Scenario)}
            aria-label="Scenario"
            style={{ padding: '0.25rem', borderRadius: '4px', border: '1px solid #d1d5db' }}
          >
            <option value="Custom">Custom</option>
            <option value="Good">Good</option>
            <option value="Better">Better</option>
            <option value="Best">Best</option>
          </select>
        </label>
      </div>

      {/* 💰 Income Drivers Section - Enhanced with sliders */}
      <div style={{ 
        marginBottom: '1.5rem',
        border: '1px solid #d1d5db',
        borderRadius: '8px',
        padding: '1rem',
        backgroundColor: '#fafafa'
      }}>
        <div style={{ 
          display: 'flex', 
          alignItems: 'center', 
          marginBottom: '1rem',
          fontWeight: 600,
          color: '#059669',
          fontSize: '1.1rem',
          borderBottom: '2px solid #059669',
          paddingBottom: '0.25rem'
        }}>
          💰 Income Drivers
        </div>

        {/* Average Net Fee with Manual Input + Slider */}
        <div style={{ marginBottom: '0.75rem' }}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr auto', gap: '0.5rem', alignItems: 'center', marginBottom: '0.5rem' }}>
            <label style={{ fontSize: '0.9rem', fontWeight: 500 }}>
              Average Net Fee
            </label>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <span style={{ fontSize: '0.8rem', color: '#6b7280' }}>$</span>
              <input
                type="number"
                min="50"
                max="500"
                step="1"
                value={avgNetFee}
                onChange={(e) => setANF(Number(e.target.value) || 50)}
                placeholder="125"
                style={{
                  width: '80px',
                  padding: '0.25rem',
                  border: '1px solid #d1d5db',
                  borderRadius: '4px',
                  fontSize: '0.8rem',
                  textAlign: 'right'
                }}
              />
            </div>
          </div>
          <input
            type="range"
            min="50"
            max="500"
            step="1"
            value={avgNetFee}
            onChange={(e) => setANF(Number(e.target.value))}
            style={{ width: '100%', marginBottom: '0.25rem' }}
          />
          <div style={{ fontSize: '0.75rem', color: '#6b7280', textAlign: 'center' }}>
            Range: $50 - $500
          </div>
        </div>

        {/* Tax-Prep Returns with Manual Input + Slider */}
        <div style={{ marginBottom: '0.75rem' }}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr auto', gap: '0.5rem', alignItems: 'center', marginBottom: '0.5rem' }}>
            <label style={{ fontSize: '0.9rem', fontWeight: 500 }}>
              Tax-Prep Returns
            </label>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <span style={{ fontSize: '0.8rem', color: '#6b7280' }}>#</span>
              <input
                type="number"
                min="100"
                max="10000"
                step="1"
                value={taxPrepReturns}
                onChange={(e) => setReturns(Number(e.target.value) || 100)}
                placeholder="1600"
                style={{
                  width: '100px',
                  padding: '0.25rem',
                  border: '1px solid #d1d5db',
                  borderRadius: '4px',
                  fontSize: '0.8rem',
                  textAlign: 'right'
                }}
              />
            </div>
          </div>
          <input
            type="range"
            min="100"
            max="5000"
            step="1"
            value={taxPrepReturns}
            onChange={(e) => setReturns(Number(e.target.value))}
            style={{ width: '100%', marginBottom: '0.25rem' }}
          />
          <div style={{ fontSize: '0.75rem', color: '#6b7280', textAlign: 'center' }}>
            Range: 100 - 5,000
          </div>
        </div>

        {/* TaxRush Returns - Blue Boxed for Canada with Slider */}
        {region === 'CA' && (
          <div style={{
            border: '2px solid #3b82f6',
            borderRadius: '8px',
            padding: '0.75rem',
            backgroundColor: '#f8fafc',
            marginBottom: '0.75rem'
          }}>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr auto', gap: '0.5rem', alignItems: 'center', marginBottom: '0.5rem' }}>
              <label style={{ fontSize: '0.9rem', fontWeight: 500 }}>
                TaxRush Returns
              </label>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <span style={{ fontSize: '0.8rem', color: '#6b7280' }}>#</span>
                <input
                  type="number"
                  min="0"
                  max="1000"
                  step="1"
                  value={taxRushReturns}
                  onChange={(e) => setTaxRush(Number(e.target.value) || 0)}
                  placeholder="0"
                  style={{
                    width: '80px',
                    padding: '0.25rem',
                    border: '1px solid #d1d5db',
                    borderRadius: '4px',
                    fontSize: '0.8rem',
                    textAlign: 'right',
                    backgroundColor: '#f0f9ff'
                  }}
                />
              </div>
            </div>
            <input
              type="range"
              min="0"
              max="1000"
              step="1"
              value={taxRushReturns}
              onChange={(e) => setTaxRush(Number(e.target.value))}
              style={{ width: '100%', marginBottom: '0.25rem' }}
            />
            <div style={{ fontSize: '0.75rem', color: '#6b7280', textAlign: 'center' }}>
              Range: 0 - 1,000
            </div>
          </div>
        )}

        {/* Customer Discounts - Dual Dollar/Percentage with Slider */}
        <div style={{ marginBottom: '0.75rem' }}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr auto', gap: '0.5rem', alignItems: 'center', marginBottom: '0.5rem' }}>
            <label style={{ fontSize: '0.9rem', fontWeight: 500 }}>
              Customer Discounts
            </label>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                <span style={{ fontSize: '0.8rem', color: '#6b7280' }}>$</span>
                <input
                  type="number"
                  min="0"
                  step="1"
                  value={Math.round(discountDollarAmount) || ''}
                  onChange={(e) => handleDiscountDollarChange(Number(e.target.value) || 0)}
                  placeholder="0"
                  style={{
                    width: '80px',
                    padding: '0.25rem',
                    border: '1px solid #d1d5db',
                    borderRadius: '4px',
                    fontSize: '0.8rem',
                    textAlign: 'right'
                  }}
                />
              </div>
              <span style={{ color: '#6b7280' }}>⟷</span>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                <input
                  type="number"
                  min="0"
                  max="50"
                  step="0.1"
                  value={discountsPct || ''}
                  onChange={(e) => handleDiscountPctChange(Number(e.target.value) || 0)}
                  placeholder="3"
                  style={{
                    width: '60px',
                    padding: '0.25rem',
                    border: '1px solid #d1d5db',
                    borderRadius: '4px',
                    fontSize: '0.8rem',
                    textAlign: 'right'
                  }}
                />
                <span style={{ fontSize: '0.8rem', color: '#6b7280' }}>%</span>
              </div>
            </div>
          </div>
          <input
            type="range"
            min="0"
            max="25"
            step="1"
            value={discountsPct}
            onChange={(e) => handleDiscountPctChange(Number(e.target.value))}
            style={{ width: '100%', marginBottom: '0.25rem' }}
          />
          <div style={{ fontSize: '0.75rem', color: '#6b7280', textAlign: 'center' }}>
            Range: 0% - 25%
          </div>
        </div>
      </div>


      {/* Expense Management Section - Flattened like Income Drivers */}
      <div style={{ 
        marginBottom: '1.5rem',
        border: '1px solid #d1d5db',
        borderRadius: '8px',
        padding: '1rem',
        backgroundColor: '#fafafa'
      }}>
        <div style={{ 
          display: 'flex', 
          alignItems: 'center', 
          marginBottom: '1rem',
          fontWeight: 600,
          color: '#6b7280',
          fontSize: '1.1rem',
          borderBottom: '2px solid #6b7280',
          paddingBottom: '0.25rem'
        }}>
          📊 Expense Management
        </div>
        
        <div>
          {(() => {
            // Get all expense fields filtered by region and TaxRush
            const allExpenseFields = expenseFields.filter(field => {
              // First filter by region
              const regionMatch = !field.regionSpecific || field.regionSpecific === region || field.regionSpecific === 'both'
              if (!regionMatch) return false
              
              // Then filter out TaxRush-related fields if handlesTaxRush is false
              const isTaxRushField = field.id === 'taxRushRoyaltiesPct' || field.id === 'taxRushShortagesPct'
              if (isTaxRushField && handlesTaxRush === false) return false
              
              return true
            })
            
            // Debug logging
            console.log('🔍 All Expense Fields:', {
              region,
              handlesTaxRush,
              totalFields: expenseFields.length,
              filteredFields: allExpenseFields.length,
              fieldIds: allExpenseFields.map(f => f.id)
            })
            
            return allExpenseFields.map(renderExpenseFieldWithSlider)
          })()}
        </div>
      </div>
    </div>
  )
}
