// angular/src/app/pages/dashboard/components/projected-performance-panel.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { CommonModule, CurrencyPipe, DecimalPipe } from '@angular/common';

// Define data interfaces for the component
export interface ProjectedPerformanceData {
  // Projected performance (current inputs)
  grossFees: number;
  discounts: number;
  taxPrepIncome: number;
  taxRushIncome: number;
  totalRevenue: number;
  totalExpenses: number;
  netIncome: number;
  netMarginPct: number;
  costPerReturn: number;
  totalReturns: number;
  region: string;

  // Prior Year data (from wizard answers)
  lastYearRevenue?: number;
  lastYearExpenses?: number;
  lastYearReturns?: number;
  expectedGrowthPct?: number;
  handlesTaxRush?: boolean;
}

export interface PerformanceStatus {
  status: 'excellent' | 'good' | 'fair' | 'poor' | 'neutral';
  color: string;
  icon: string;
}

@Component({
  selector: 'app-projected-performance-panel',
  standalone: true,
  imports: [CommonModule, CurrencyPipe, DecimalPipe],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="performance-panel">
      <div class="panel-header">
        <span class="panel-icon">📈</span>
        <span class="panel-title">PY Performance</span>
      </div>

      <!-- Last Year Performance Section -->
      <div 
        *ngIf="showPriorYearData"
        class="prior-year-section"
      >
        <div class="section-header">
          📅 Last Year Performance
        </div>

        <!-- Prior Year Net Margin -->
        <div 
          class="metric-card"
          [style.background-color]="pyNetMarginStatus.color + '15'"
          [style.border-color]="pyNetMarginStatus.color"
        >
          <span class="metric-icon">{{ pyNetMarginStatus.icon }}</span>
          <div class="metric-content">
            <div class="metric-label">PY Net Margin</div>
            <div 
              class="metric-value"
              [style.color]="pyNetMarginStatus.color"
            >
              {{ pyNetMarginPct | number:'1.1-1' }}%
            </div>
          </div>
        </div>

        <!-- Prior Year Cost Per Return -->
        <div 
          class="metric-card"
          [style.background-color]="pyCostPerReturnStatus.color + '15'"
          [style.border-color]="pyCostPerReturnStatus.color"
        >
          <span class="metric-icon">{{ pyCostPerReturnStatus.icon }}</span>
          <div class="metric-content">
            <div class="metric-label">PY Cost / Return</div>
            <div 
              class="metric-value"
              [style.color]="pyCostPerReturnStatus.color"
            >
              {{ pyCostPerReturn | currency }}
            </div>
          </div>
        </div>

        <!-- Prior Year Summary Details -->
        <div class="summary-details">
          <div class="detail-row">Revenue: {{ data.lastYearRevenue | currency }}</div>
          <div class="detail-row">Expenses: {{ data.lastYearExpenses | currency }}</div>
          <div class="detail-row">Returns: {{ data.lastYearReturns | number }}</div>
        </div>
      </div>

      <!-- Future Enhancement Placeholder -->
      <!-- 
      TODO: FUTURE ENHANCEMENT - Projected Performance Goals Section
      
      When transitioning from forecasting to tracking mode, restore this section:
      - Target Net Margin (Reference) with calculated projections
      - Target Cost/Return (Reference) with performance targets  
      - Performance Change display from Page 1 expectedGrowthPct
      - Static reference metrics for PY vs Projected vs Actual comparisons
      
      This will be valuable when users start entering actual numbers to compare
      against their forecasted targets and see performance variance.
      -->
    </div>
  `,
  styles: [`
    .performance-panel {
      min-width: 300px;
      max-width: 350px;
      background: white;
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
      padding: 1rem;
    }

    .panel-header {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      color: #0369a1;
      margin-bottom: 1rem;
    }

    .panel-icon {
      font-size: 1.2rem;
    }

    .panel-title {
      font-size: 1.1rem;
      font-weight: 600;
      margin: 0;
    }

    .prior-year-section {
      margin-bottom: 1rem;
    }

    .section-header {
      font-weight: bold;
      font-size: 0.9rem;
      color: #6b7280;
      margin-bottom: 0.5rem;
      border-bottom: 1px solid #d1d5db;
      padding-bottom: 0.25rem;
    }

    .metric-card {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      padding: 0.4rem;
      border: 1px solid;
      border-radius: 6px;
      margin-bottom: 0.4rem;
    }

    .metric-icon {
      font-size: 1rem;
    }

    .metric-content {
      flex: 1;
    }

    .metric-label {
      font-size: 0.8rem;
      color: #374151;
      font-weight: 500;
      margin-bottom: 0.25rem;
    }

    .metric-value {
      font-size: 0.9rem;
      font-weight: bold;
    }

    .summary-details {
      font-size: 0.75rem;
      color: #6b7280;
      line-height: 1.4;
      margin-bottom: 0.5rem;
    }

    .detail-row {
      margin-bottom: 0.1rem;
    }

    /* Responsive adjustments */
    @media (max-width: 480px) {
      .performance-panel {
        min-width: auto;
        max-width: none;
      }
    }
  `]
})
export class ProjectedPerformancePanelComponent {
  @Input() data!: ProjectedPerformanceData;

  // Calculate prior year metrics
  get pyNetIncome(): number {
    return (this.data.lastYearRevenue || 0) - (this.data.lastYearExpenses || 0);
  }

  get pyNetMarginPct(): number {
    const revenue = this.data.lastYearRevenue || 0;
    return revenue > 0 ? (this.pyNetIncome / revenue) * 100 : 0;
  }

  get pyCostPerReturn(): number {
    const returns = this.data.lastYearReturns || 0;
    const expenses = this.data.lastYearExpenses || 0;
    return returns > 0 ? expenses / returns : 0;
  }

  get showPriorYearData(): boolean {
    return (this.data.lastYearRevenue || 0) > 0 && (this.data.lastYearExpenses || 0) > 0;
  }

  // Performance status calculation
  get pyNetMarginStatus(): PerformanceStatus {
    return this.getPerformanceStatus('netMargin', this.pyNetMarginPct);
  }

  get pyCostPerReturnStatus(): PerformanceStatus {
    return this.getPerformanceStatus('costPerReturn', this.pyCostPerReturn);
  }

  private getPerformanceStatus(metric: string, value: number): PerformanceStatus {
    switch (metric) {
      case 'netMargin':
        if (value >= 20) return { status: 'excellent', color: '#059669', icon: '🎯' };
        if (value >= 15) return { status: 'good', color: '#0369a1', icon: '✅' };
        if (value >= 10) return { status: 'fair', color: '#d97706', icon: '⚠️' };
        return { status: 'poor', color: '#dc2626', icon: '🚨' };

      case 'costPerReturn':
        if (value <= 85) return { status: 'excellent', color: '#059669', icon: '🎯' };
        if (value <= 100) return { status: 'good', color: '#0369a1', icon: '✅' };
        if (value <= 120) return { status: 'fair', color: '#d97706', icon: '⚠️' };
        return { status: 'poor', color: '#dc2626', icon: '🚨' };

      default:
        return { status: 'neutral', color: '#6b7280', icon: '📊' };
    }
  }
}

// src/components/ProjectedPerformancePanel.tsx
// ProjectedPerformancePanel.tsx - Prior Year vs Projected performance comparison
// Shows last year performance metrics vs projected goals

import React from 'react'
import { currency, pct } from '../hooks/useCalculations'

interface ProjectedPerformancePanelProps {
  // Projected performance (current inputs)
  grossFees: number
  discounts: number
  taxPrepIncome: number
  taxRushIncome: number
  totalRevenue: number
  totalExpenses: number
  netIncome: number
  netMarginPct: number
  costPerReturn: number
  totalReturns: number
  region: string
  
  // Prior Year data (from wizard answers)
  lastYearRevenue?: number
  lastYearExpenses?: number
  lastYearReturns?: number
  expectedGrowthPct?: number
  handlesTaxRush?: boolean
}

export default function ProjectedPerformancePanel({ 
  grossFees, 
  discounts, 
  taxPrepIncome, 
  taxRushIncome,
  totalRevenue, 
  totalExpenses, 
  netIncome, 
  netMarginPct, 
  costPerReturn, 
  totalReturns,
  region,
  lastYearRevenue = 0,
  lastYearExpenses = 0, 
  lastYearReturns = 0,
  expectedGrowthPct = 0,
  handlesTaxRush = false
}: ProjectedPerformancePanelProps) {
  
  // Calculate prior year metrics using same logic as target calculations
  // PY Net Income = Last Year Revenue - Last Year Expenses  
  const pyNetIncome = lastYearRevenue - lastYearExpenses
  
  // PY Net Margin = (PY Net Income ÷ Last Year Revenue) × 100
  const pyNetMarginPct = lastYearRevenue > 0 ? (pyNetIncome / lastYearRevenue) * 100 : 0
  
  // PY Cost Per Return = Last Year Expenses ÷ Last Year Returns
  const pyCostPerReturn = lastYearReturns > 0 ? lastYearExpenses / lastYearReturns : 0
  
  // Performance status indicators
  const getPerformanceStatus = (metric: string, value: number) => {
    switch (metric) {
      case 'netMargin':
        if (value >= 20) return { status: 'excellent', color: '#059669', icon: '🎯' }
        if (value >= 15) return { status: 'good', color: '#0369a1', icon: '✅' }
        if (value >= 10) return { status: 'fair', color: '#d97706', icon: '⚠️' }
        return { status: 'poor', color: '#dc2626', icon: '🚨' }
      
      case 'costPerReturn':
        if (value <= 85) return { status: 'excellent', color: '#059669', icon: '🎯' }
        if (value <= 100) return { status: 'good', color: '#0369a1', icon: '✅' }
        if (value <= 120) return { status: 'fair', color: '#d97706', icon: '⚠️' }
        return { status: 'poor', color: '#dc2626', icon: '🚨' }
      
      default:
        return { status: 'neutral', color: '#6b7280', icon: '📊' }
    }
  }

  const pyNetMarginStatus = getPerformanceStatus('netMargin', pyNetMarginPct)
  const pyCostPerReturnStatus = getPerformanceStatus('costPerReturn', pyCostPerReturn)
  const projectedNetMarginStatus = getPerformanceStatus('netMargin', netMarginPct)
  const projectedCostPerReturnStatus = getPerformanceStatus('costPerReturn', costPerReturn)

  return (
    <div className="card" style={{ minWidth: '300px', maxWidth: '350px' }}>
      <div className="card-title" style={{ color: '#0369a1', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
        📈 PY Performance
      </div>
      
      {/* Last Year Performance */}
      {lastYearRevenue > 0 && lastYearExpenses > 0 && (
        <div style={{ marginBottom: '1rem' }}>
          <div style={{ 
            fontWeight: 'bold', 
            fontSize: '0.9rem', 
            color: '#6b7280', 
            marginBottom: '0.5rem',
            borderBottom: '1px solid #d1d5db',
            paddingBottom: '0.25rem'
          }}>
            📅 Last Year Performance
          </div>
          
          <div style={{ 
            display: 'flex', 
            alignItems: 'center', 
            gap: '0.5rem',
            padding: '0.4rem',
            backgroundColor: `${pyNetMarginStatus.color}15`,
            border: `1px solid ${pyNetMarginStatus.color}`,
            borderRadius: '6px',
            marginBottom: '0.4rem'
          }}>
            <span style={{ fontSize: '1rem' }}>{pyNetMarginStatus.icon}</span>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: '0.8rem', color: '#374151', fontWeight: 500 }}>PY Net Margin</div>
              <div style={{ fontSize: '0.9rem', fontWeight: 'bold', color: pyNetMarginStatus.color }}>
                {pct(pyNetMarginPct)}
              </div>
            </div>
          </div>

          <div style={{ 
            display: 'flex', 
            alignItems: 'center', 
            gap: '0.5rem',
            padding: '0.4rem',
            backgroundColor: `${pyCostPerReturnStatus.color}15`,
            border: `1px solid ${pyCostPerReturnStatus.color}`,
            borderRadius: '6px',
            marginBottom: '0.5rem'
          }}>
            <span style={{ fontSize: '1rem' }}>{pyCostPerReturnStatus.icon}</span>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: '0.8rem', color: '#374151', fontWeight: 500 }}>PY Cost / Return</div>
              <div style={{ fontSize: '0.9rem', fontWeight: 'bold', color: pyCostPerReturnStatus.color }}>
                {currency(pyCostPerReturn)}
              </div>
            </div>
          </div>
          
          <div style={{ fontSize: '0.75rem', color: '#6b7280', lineHeight: '1.4' }}>
            <div>Revenue: {currency(lastYearRevenue)}</div>
            <div>Expenses: {currency(lastYearExpenses)}</div>
            <div>Returns: {lastYearReturns.toLocaleString()}</div>
          </div>
        </div>
      )}

      {/* Projected Performance Goals */}
      <div style={{ marginBottom: '1rem' }}>
        <div style={{ 
          fontWeight: 'bold', 
          fontSize: '0.9rem', 
          color: '#059669', 
          marginBottom: '0.5rem',
          borderBottom: '1px solid #d1d5db',
          paddingBottom: '0.25rem'
        }}>
          🎯 Projected Performance Goals
          {expectedGrowthPct !== 0 && (
            <div style={{ fontSize: '0.75rem', fontWeight: 'normal', color: '#6b7280', marginTop: '0.25rem' }}>
              Performance Change: {expectedGrowthPct > 0 ? '+' : ''}{expectedGrowthPct}% growth target
            </div>
          )}
        </div>
        
        <div style={{ 
          display: 'flex', 
          alignItems: 'center', 
          gap: '0.5rem',
          padding: '0.4rem',
          backgroundColor: '#f9fafb',
          border: `1px solid #e5e7eb`,
          borderRadius: '6px',
          marginBottom: '0.4rem',
          opacity: 0.8
        }}>
          <span style={{ fontSize: '1rem', color: '#6b7280' }}>📊</span>
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: '0.8rem', color: '#6b7280', fontWeight: 500 }}>Target Net Margin (Reference)</div>
            <div style={{ fontSize: '0.9rem', fontWeight: 'bold', color: '#6b7280' }}>
              {pct(netMarginPct)}
            </div>
          </div>
        </div>

        <div style={{ 
          display: 'flex', 
          alignItems: 'center', 
          gap: '0.5rem',
          padding: '0.4rem',
          backgroundColor: '#f9fafb',
          border: `1px solid #e5e7eb`,
          borderRadius: '6px',
          marginBottom: '0.5rem',
          opacity: 0.8
        }}>
          <span style={{ fontSize: '1rem', color: '#6b7280' }}>📊</span>
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: '0.8rem', color: '#6b7280', fontWeight: 500 }}>Target Cost / Return (Reference)</div>
            <div style={{ fontSize: '0.9rem', fontWeight: 'bold', color: '#6b7280' }}>
              {currency(costPerReturn)}
            </div>
          </div>
        </div>
        
        <div style={{ fontSize: '0.75rem', color: '#6b7280', lineHeight: '1.4' }}>
          <div>Target Revenue: {currency(totalRevenue)}</div>
          <div>Target Expenses: {currency(totalExpenses)}</div>
          <div>Target Returns: {totalReturns.toLocaleString()}</div>
        </div>
      </div>

    </div>
  )
}
